// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * typedef struct _opaque_pthread_rwlockattr_t {
 *     long __sig;
 *     char __opaque[16];
 * } __darwin_pthread_rwlockattr_t
 * }
 */
public class __darwin_pthread_rwlockattr_t extends _opaque_pthread_rwlockattr_t {

    __darwin_pthread_rwlockattr_t()
    {
        // Should not be called directly
    }
}
