// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * struct H5VL_link_get_args_t {
 *     H5VL_link_get_t op_type;
 *     union {
 *         struct {
 *             H5L_info2_t *linfo;
 *         } get_info;
 *         struct {
 *             size_t name_size;
 *             char *name;
 *             size_t *name_len;
 *         } get_name;
 *         struct {
 *             size_t buf_size;
 *             void *buf;
 *         } get_val;
 *     } args;
 * }
 * }
 */
public class H5VL_link_get_args_t {

    H5VL_link_get_args_t()
    {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT =
        MemoryLayout
            .structLayout(hdf5_h.C_INT.withName("op_type"), MemoryLayout.paddingLayout(4),
                          H5VL_link_get_args_t.args.layout().withName("args"))
            .withName("H5VL_link_get_args_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() { return $LAYOUT; }

    private static final OfInt op_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("op_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5VL_link_get_t op_type
     * }
     */
    public static final OfInt op_type$layout() { return op_type$LAYOUT; }

    private static final long op_type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5VL_link_get_t op_type
     * }
     */
    public static final long op_type$offset() { return op_type$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5VL_link_get_t op_type
     * }
     */
    public static int op_type(MemorySegment struct) { return struct.get(op_type$LAYOUT, op_type$OFFSET); }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5VL_link_get_t op_type
     * }
     */
    public static void op_type(MemorySegment struct, int fieldValue)
    {
        struct.set(op_type$LAYOUT, op_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct {
     *         H5L_info2_t *linfo;
     *     } get_info;
     *     struct {
     *         size_t name_size;
     *         char *name;
     *         size_t *name_len;
     *     } get_name;
     *     struct {
     *         size_t buf_size;
     *         void *buf;
     *     } get_val;
     * }
     * }
     */
    public static class args {

        args()
        {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT =
            MemoryLayout
                .unionLayout(H5VL_link_get_args_t.args.get_info.layout().withName("get_info"),
                             H5VL_link_get_args_t.args.get_name.layout().withName("get_name"),
                             H5VL_link_get_args_t.args.get_val.layout().withName("get_val"))
                .withName("$anon$614:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() { return $LAYOUT; }

        /**
         * {@snippet lang=c :
         * struct {
         *     H5L_info2_t *linfo;
         * }
         * }
         */
        public static class get_info {

            get_info()
            {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT =
                MemoryLayout.structLayout(hdf5_h.C_POINTER.withName("linfo")).withName("$anon$616:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() { return $LAYOUT; }

            private static final AddressLayout linfo$LAYOUT =
                (AddressLayout)$LAYOUT.select(groupElement("linfo"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * H5L_info2_t *linfo
             * }
             */
            public static final AddressLayout linfo$layout() { return linfo$LAYOUT; }

            private static final long linfo$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * H5L_info2_t *linfo
             * }
             */
            public static final long linfo$offset() { return linfo$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * H5L_info2_t *linfo
             * }
             */
            public static MemorySegment linfo(MemorySegment struct)
            {
                return struct.get(linfo$LAYOUT, linfo$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * H5L_info2_t *linfo
             * }
             */
            public static void linfo(MemorySegment struct, MemorySegment fieldValue)
            {
                struct.set(linfo$LAYOUT, linfo$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index)
            {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator)
            {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
            {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout get_info$LAYOUT =
            (GroupLayout)$LAYOUT.select(groupElement("get_info"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     H5L_info2_t *linfo;
         * } get_info
         * }
         */
        public static final GroupLayout get_info$layout() { return get_info$LAYOUT; }

        private static final long get_info$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     H5L_info2_t *linfo;
         * } get_info
         * }
         */
        public static final long get_info$offset() { return get_info$OFFSET; }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     H5L_info2_t *linfo;
         * } get_info
         * }
         */
        public static MemorySegment get_info(MemorySegment union)
        {
            return union.asSlice(get_info$OFFSET, get_info$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     H5L_info2_t *linfo;
         * } get_info
         * }
         */
        public static void get_info(MemorySegment union, MemorySegment fieldValue)
        {
            MemorySegment.copy(fieldValue, 0L, union, get_info$OFFSET, get_info$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     size_t name_size;
         *     char *name;
         *     size_t *name_len;
         * }
         * }
         */
        public static class get_name {

            get_name()
            {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT =
                MemoryLayout
                    .structLayout(hdf5_h.C_LONG.withName("name_size"), hdf5_h.C_POINTER.withName("name"),
                                  hdf5_h.C_POINTER.withName("name_len"))
                    .withName("$anon$621:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() { return $LAYOUT; }

            private static final OfLong name_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("name_size"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * size_t name_size
             * }
             */
            public static final OfLong name_size$layout() { return name_size$LAYOUT; }

            private static final long name_size$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * size_t name_size
             * }
             */
            public static final long name_size$offset() { return name_size$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * size_t name_size
             * }
             */
            public static long name_size(MemorySegment struct)
            {
                return struct.get(name_size$LAYOUT, name_size$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * size_t name_size
             * }
             */
            public static void name_size(MemorySegment struct, long fieldValue)
            {
                struct.set(name_size$LAYOUT, name_size$OFFSET, fieldValue);
            }

            private static final AddressLayout name$LAYOUT =
                (AddressLayout)$LAYOUT.select(groupElement("name"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * char *name
             * }
             */
            public static final AddressLayout name$layout() { return name$LAYOUT; }

            private static final long name$OFFSET = 8;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * char *name
             * }
             */
            public static final long name$offset() { return name$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * char *name
             * }
             */
            public static MemorySegment name(MemorySegment struct)
            {
                return struct.get(name$LAYOUT, name$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * char *name
             * }
             */
            public static void name(MemorySegment struct, MemorySegment fieldValue)
            {
                struct.set(name$LAYOUT, name$OFFSET, fieldValue);
            }

            private static final AddressLayout name_len$LAYOUT =
                (AddressLayout)$LAYOUT.select(groupElement("name_len"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * size_t *name_len
             * }
             */
            public static final AddressLayout name_len$layout() { return name_len$LAYOUT; }

            private static final long name_len$OFFSET = 16;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * size_t *name_len
             * }
             */
            public static final long name_len$offset() { return name_len$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * size_t *name_len
             * }
             */
            public static MemorySegment name_len(MemorySegment struct)
            {
                return struct.get(name_len$LAYOUT, name_len$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * size_t *name_len
             * }
             */
            public static void name_len(MemorySegment struct, MemorySegment fieldValue)
            {
                struct.set(name_len$LAYOUT, name_len$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index)
            {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator)
            {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
            {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout get_name$LAYOUT =
            (GroupLayout)$LAYOUT.select(groupElement("get_name"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     size_t name_size;
         *     char *name;
         *     size_t *name_len;
         * } get_name
         * }
         */
        public static final GroupLayout get_name$layout() { return get_name$LAYOUT; }

        private static final long get_name$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     size_t name_size;
         *     char *name;
         *     size_t *name_len;
         * } get_name
         * }
         */
        public static final long get_name$offset() { return get_name$OFFSET; }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     size_t name_size;
         *     char *name;
         *     size_t *name_len;
         * } get_name
         * }
         */
        public static MemorySegment get_name(MemorySegment union)
        {
            return union.asSlice(get_name$OFFSET, get_name$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     size_t name_size;
         *     char *name;
         *     size_t *name_len;
         * } get_name
         * }
         */
        public static void get_name(MemorySegment union, MemorySegment fieldValue)
        {
            MemorySegment.copy(fieldValue, 0L, union, get_name$OFFSET, get_name$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     size_t buf_size;
         *     void *buf;
         * }
         * }
         */
        public static class get_val {

            get_val()
            {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT =
                MemoryLayout
                    .structLayout(hdf5_h.C_LONG.withName("buf_size"), hdf5_h.C_POINTER.withName("buf"))
                    .withName("$anon$628:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() { return $LAYOUT; }

            private static final OfLong buf_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("buf_size"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * size_t buf_size
             * }
             */
            public static final OfLong buf_size$layout() { return buf_size$LAYOUT; }

            private static final long buf_size$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * size_t buf_size
             * }
             */
            public static final long buf_size$offset() { return buf_size$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * size_t buf_size
             * }
             */
            public static long buf_size(MemorySegment struct)
            {
                return struct.get(buf_size$LAYOUT, buf_size$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * size_t buf_size
             * }
             */
            public static void buf_size(MemorySegment struct, long fieldValue)
            {
                struct.set(buf_size$LAYOUT, buf_size$OFFSET, fieldValue);
            }

            private static final AddressLayout buf$LAYOUT =
                (AddressLayout)$LAYOUT.select(groupElement("buf"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * void *buf
             * }
             */
            public static final AddressLayout buf$layout() { return buf$LAYOUT; }

            private static final long buf$OFFSET = 8;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * void *buf
             * }
             */
            public static final long buf$offset() { return buf$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * void *buf
             * }
             */
            public static MemorySegment buf(MemorySegment struct)
            {
                return struct.get(buf$LAYOUT, buf$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * void *buf
             * }
             */
            public static void buf(MemorySegment struct, MemorySegment fieldValue)
            {
                struct.set(buf$LAYOUT, buf$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index)
            {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator)
            {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
            {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout get_val$LAYOUT =
            (GroupLayout)$LAYOUT.select(groupElement("get_val"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     size_t buf_size;
         *     void *buf;
         * } get_val
         * }
         */
        public static final GroupLayout get_val$layout() { return get_val$LAYOUT; }

        private static final long get_val$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     size_t buf_size;
         *     void *buf;
         * } get_val
         * }
         */
        public static final long get_val$offset() { return get_val$OFFSET; }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     size_t buf_size;
         *     void *buf;
         * } get_val
         * }
         */
        public static MemorySegment get_val(MemorySegment union)
        {
            return union.asSlice(get_val$OFFSET, get_val$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     size_t buf_size;
         *     void *buf;
         * } get_val
         * }
         */
        public static void get_val(MemorySegment union, MemorySegment fieldValue)
        {
            MemorySegment.copy(fieldValue, 0L, union, get_val$OFFSET, get_val$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index)
        {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator)
        {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
        {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                Consumer<MemorySegment> cleanup)
        {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                Consumer<MemorySegment> cleanup)
        {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout args$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("args"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         H5L_info2_t *linfo;
     *     } get_info;
     *     struct {
     *         size_t name_size;
     *         char *name;
     *         size_t *name_len;
     *     } get_name;
     *     struct {
     *         size_t buf_size;
     *         void *buf;
     *     } get_val;
     * } args
     * }
     */
    public static final GroupLayout args$layout() { return args$LAYOUT; }

    private static final long args$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         H5L_info2_t *linfo;
     *     } get_info;
     *     struct {
     *         size_t name_size;
     *         char *name;
     *         size_t *name_len;
     *     } get_name;
     *     struct {
     *         size_t buf_size;
     *         void *buf;
     *     } get_val;
     * } args
     * }
     */
    public static final long args$offset() { return args$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         H5L_info2_t *linfo;
     *     } get_info;
     *     struct {
     *         size_t name_size;
     *         char *name;
     *         size_t *name_len;
     *     } get_name;
     *     struct {
     *         size_t buf_size;
     *         void *buf;
     *     } get_val;
     * } args
     * }
     */
    public static MemorySegment args(MemorySegment struct)
    {
        return struct.asSlice(args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         H5L_info2_t *linfo;
     *     } get_info;
     *     struct {
     *         size_t name_size;
     *         char *name;
     *         size_t *name_len;
     *     } get_name;
     *     struct {
     *         size_t buf_size;
     *         void *buf;
     *     } get_val;
     * } args
     * }
     */
    public static void args(MemorySegment struct, MemorySegment fieldValue)
    {
        MemorySegment.copy(fieldValue, 0L, struct, args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index)
    {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate(layout()); }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
    {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
    {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                            Consumer<MemorySegment> cleanup)
    {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
