// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * typedef __darwin_pthread_condattr_t pthread_condattr_t
 * }
 */
public class pthread_condattr_t extends _opaque_pthread_condattr_t {

    pthread_condattr_t()
    {
        // Should not be called directly
    }
}
