// Generated by jextract

package org.hdfgroup.javahdf5;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef __darwin_pthread_rwlock_t pthread_rwlock_t
 * }
 */
public class pthread_rwlock_t extends _opaque_pthread_rwlock_t {

    pthread_rwlock_t() {
        // Should not be called directly
    }
}

