#define H5_mask ID_H5_c
#define H5A_mask ID_H5A_c
#define H5AC_mask ID_H5AC_c
#define H5B_mask ID_H5B_c
#define H5D_mask ID_H5D_c
#define H5Dio_mask ID_H5Dio_c
#define H5E_mask ID_H5E_c
#define H5F_mask ID_H5F_c
#define H5FD_mask ID_H5FD_c
#define H5FD_core_mask ID_H5FD_core_c
#define H5FD_family_mask ID_H5FD_family_c
#define H5FD_fphdf5_mask ID_H5FD_fphdf5_c
#define H5FD_gass_mask ID_H5FD_gass_c
#define H5FD_log_mask ID_H5FD_log_c
#define H5FD_mpio_mask ID_H5FD_mpio_c
#define H5FD_mpiposix_mask ID_H5FD_mpiposix_c
#define H5FD_sec2_mask ID_H5FD_sec2_c
#define H5FD_srb_mask ID_H5FD_srb_c
#define H5FL_mask ID_H5FL_c
#define H5FO_mask ID_H5FO_c
#define H5FP_mask ID_H5FP_c
#define H5FPclient_mask ID_H5FPclient_c
#define H5FPserver_mask ID_H5FPserver_c
#define H5FS_mask ID_H5FS_c
#define H5Fcompact_mask ID_H5Fcompact_c
#define H5Fcontig_mask ID_H5Fcontig_c
#define H5Fdbg_mask ID_H5Fdbg_c
#define H5Fistore_mask ID_H5Fistore_c
#define H5Fseq_mask ID_H5Fseq_c
#define H5G_mask ID_H5G_c
#define H5G_ent_mask ID_H5G_ent_c
#define H5G_node_mask ID_H5G_node_c
#define H5G_stab_mask ID_H5G_stab_c
#define H5HG_mask ID_H5HG_c
#define H5HGdbg_mask ID_H5HGdbg_c
#define H5HL_mask ID_H5HL_c
#define H5HLdbg_mask ID_H5HLdbg_c
#define H5HP_mask ID_H5HP_c
#define H5I_mask ID_H5I_c
#define H5MF_mask ID_H5MF_c
#define H5MM_mask ID_H5MM_c
#define H5O_mask ID_H5O_c
#define H5O_attr_mask ID_H5O_attr_c
#define H5O_bogus_mask ID_H5O_bogus_c
#define H5O_cont_mask ID_H5O_cont_c
#define H5O_dtype_mask ID_H5O_dtype_c
#define H5O_efl_mask ID_H5O_efl_c
#define H5O_fill_mask ID_H5O_fill_c
#define H5O_layout_mask ID_H5O_layout_c
#define H5O_mtime_mask ID_H5O_mtime_c
#define H5O_name_mask ID_H5O_name_c
#define H5O_null_mask ID_H5O_null_c
#define H5O_pline_mask ID_H5O_pline_c
#define H5O_sdspace_mask ID_H5O_sdspace_c
#define H5O_shared_mask ID_H5O_shared_c
#define H5O_stab_mask ID_H5O_stab_c
#define H5P_mask ID_H5P_c
#define H5Pdcpl_mask ID_H5Pdcpl_c
#define H5Pdxpl_mask ID_H5Pdxpl_c
#define H5Pfapl_mask ID_H5Pfapl_c
#define H5Pfcpl_mask ID_H5Pfcpl_c
#define H5Ptest_mask ID_H5Ptest_c
#define H5R_mask ID_H5R_c
#define H5RS_mask ID_H5RS_c
#define H5S_mask ID_H5S_c
#define H5ST_mask ID_H5ST_c
#define H5Sall_mask ID_H5Sall_c
#define H5Shyper_mask ID_H5Shyper_c
#define H5Sall_mask ID_H5Sall_c
#define H5Snone_mask ID_H5Snone_c
#define H5Spoint_mask ID_H5Spoint_c
#define H5Sselect_mask ID_H5Sselect_c
#define H5Stest_mask ID_H5Stest_c
#define H5T_mask ID_H5T_c
#define H5TB_mask ID_H5TB_c
#define H5Tarray_mask ID_H5Tarray_c
#define H5Tbit_mask ID_H5Tbit_c
#define H5Tcommit_mask ID_H5Tcommit_c
#define H5Tcompound_mask ID_H5Tcompound_c
#define H5Tconv_mask ID_H5Tconv_c
#define H5Tcset_mask ID_H5Tcset_c
#define H5Tenum_mask ID_H5Tenum_c
#define H5Tfields_mask ID_H5Tfields_c
#define H5Tfixed_mask ID_H5Tfixed_c
#define H5Tfloat_mask ID_H5Tfloat_c
#define H5Tnative_mask ID_H5Tnative_c
#define H5Toffset_mask ID_H5Toffset_c
#define H5Topaque_mask ID_H5Topaque_c
#define H5Torder_mask ID_H5Torder_c
#define H5Tpad_mask ID_H5Tpad_c
#define H5Tprecis_mask ID_H5Tprecis_c
#define H5Tstrpad_mask ID_H5Tstrpad_c
#define H5Tvlen_mask ID_H5Tvlen_c
#define H5V_mask ID_H5V_c
#define H5Z_mask ID_H5Z_c
#define H5Z_deflate_mask ID_H5Z_deflate_c
#define H5Z_fletcher32_mask ID_H5Z_fletcher32_c
#define H5Z_shuffle_mask ID_H5Z_shuffle_c
#define H5Z_szip_mask ID_H5Z_szip_c
#define H5Tinit_mask ID_H5Tinit_c
