name: 'Setup Doxygen'
description: 'Install Doxygen with version that supports Fortran cross-references'
inputs:
  version:
    description: 'Doxygen version to install'
    required: false
    default: '1.16.0'
runs:
  using: 'composite'
  steps:
    - name: Install Doxygen
      uses: ssciwr/doxygen-install@ad81ff239f3be5262e2577abce2d728c426fcc59 # v2.0.0
      with:
        version: ${{ inputs.version }}
