var searchData=
[
  ['c_0',['C',['../_g_l_s.html#GLS_C',1,'C'],['../_h5_v_l__u_g.html#subsubsec_vol_lang_c',1,'C++'],['../_intro_par_cont_hyperslab.html#secIntroParContHyperslabC',1,'Writing a Contiguous Hyperslab in C'],['../_intro_par_regular_spaced.html#secIntroParRegularSpacedC',1,'Writing Regularly Spaced Columns in C']]],
  ['c_20api_1',['HDF5 C API',['../_l_b_a_p_i.html#secLBAPI',1,'']]],
  ['c_20api_20call_20semantics_2',['C API Call Semantics',['../_h5_f_i_m__u_g.html#subsec_file_image_semantics',1,'']]],
  ['c_20api_20call_20syntax_3',['File Image C API Call Syntax',['../_h5_f_i_m__u_g.html#subsec_file_image_api',1,'']]],
  ['c_20api_20introduction_4',['C++ API Introduction',['../h5_cpp_intro.html',1,'']]],
  ['c_20api_20routine_5',['High-level C API Routine',['../_h5_f_i_m__u_g.html#subsubsec_file_image_api_high',1,'']]],
  ['c_20api_20routines_6',['Low-level C API Routines',['../_h5_f_i_m__u_g.html#subsubsec_file_image_api_low',1,'']]],
  ['c_20api_20to_20c_20class_20mapping_7',['C API to C++ Class Mapping',['../h5_cpp_intro.html#cpp_mapping',1,'']]],
  ['c_20changes_20for_20hdf5_201_2012_8',['C Changes for HDF5 1 12',['../_f_m_t3.html#subsec_fmt3_intro_112',1,'I.C. Changes for HDF5 1.12'],['../_f_m_t4.html#subsec_fmt4_intro_112',1,'I.C. Changes for HDF5 1.12']]],
  ['c_20class_20mapping_9',['C API to C++ Class Mapping',['../h5_cpp_intro.html#cpp_mapping',1,'']]],
  ['c_20developers_20using_20c_20functions_10',['Programming Note for C++ Developers Using C Functions',['../_v_f_l_t_n.html#subsec_vfl_reg_prog',1,'']]],
  ['c_20disk_20format_3a_20level_200c_20superblock_20extension_11',['C Disk Format: Level 0C Superblock Extension',['../_f_m_t2.html#subsec_fmt2_boot_supext',1,'II.C. Disk Format: Level 0C - Superblock Extension'],['../_f_m_t3.html#subsec_fmt3_boot_supext',1,'II.C. Disk Format: Level 0C - Superblock Extension'],['../_f_m_t4.html#subsec_fmt4_boot_supext',1,'II.C. Disk Format: Level 0C - Superblock Extension']]],
  ['c_20disk_20format_3a_20level_201c_20symbol_20table_20entry_12',['C Disk Format: Level 1C Symbol Table Entry',['../_f_m_t2.html#subsec_fmt2_infra_symboltableentry',1,'III.C. Disk Format: Level 1C - Symbol Table Entry'],['../_f_m_t3.html#subsec_fmt3_infra_symboltableentry',1,'III.C. Disk Format: Level 1C - Symbol Table Entry'],['../_f_m_t4.html#subsec_fmt4_infra_symboltableentry',1,'III.C. Disk Format: Level 1C - Symbol Table Entry']]],
  ['c_20function_13',['New C Function',['../rel_spec_18.html#subsubsec_rel_spec_18_change_5_new',1,'']]],
  ['c_20functions_14',['C Functions',['../rel_spec_18.html#subsubsec_rel_spec_18_change_8_new',1,'New C Functions'],['../_v_f_l_t_n.html#subsec_vfl_reg_prog',1,'Programming Note for C++ Developers Using C Functions']]],
  ['c_20functions_20and_20macros_15',['New C Functions and Macros',['../rel_spec_18.html#subsubsec_rel_spec_18_change_7_new',1,'']]],
  ['c_20native_20vol_20connector_20optional_20values_20by_20subclass_16',['Appendix C Native VOL Connector Optional Values By Subclass',['../_v_o_l__connector.html#secVOLAppC',1,'']]],
  ['c_20reference_20encoding_20backward_20compatibility_17',['VIII.C. Reference Encoding (Backward Compatibility)',['../_f_m_t3.html#subsec_fmt3_appendixd_encodedp',1,'']]],
  ['c_20reference_20encoding_20revised_18',['VIII.C. Reference Encoding (Revised)',['../_f_m_t4.html#subsec_fmt4_appendixd_encoderv',1,'']]],
  ['c_20run‐time_20everywhere_19',['Use the Same Memory Manager/Correct C Run‐time Everywhere',['../freeing_memory.html#subsec_freeing_memory_mitigation1',1,'']]],
  ['c_20run_20time_20crt_20',['The Windows C Run-time (CRT)',['../freeing_memory.html#sec_freeing_memory_crt',1,'']]],
  ['c_20the_20fixed_20array_20index_21',['C The Fixed Array Index',['../_f_m_t3.html#subsec_fmt3_appendixc_fixedarr',1,'VII.C. The Fixed Array Index'],['../_f_m_t4.html#subsec_fmt4_appendixc_fixedarr',1,'VII.C. The Fixed Array Index']]],
  ['c_20the_20link_20info_20message_22',['c The Link Info Message',['../_f_m_t2.html#subsubsec_fmt2_dataobject_hdr_msg_linkinfo',1,'IV.A.2.c. The Link Info Message'],['../_f_m_t3.html#subsubsec_fmt3_dataobject_hdr_msg_linkinfo',1,'IV.A.2.c. The Link Info Message'],['../_f_m_t4.html#subsubsec_fmt4_dataobject_hdr_msg_linkinfo',1,'IV.A.2.c. The Link Info Message']]],
  ['c_3a_20types_20of_20indexes_20for_20dataset_20chunks_23',['C: Types of Indexes for Dataset Chunks',['../_f_m_t3.html#sec_fmt3_appendixc',1,'VII. Appendix C: Types of Indexes for Dataset Chunks'],['../_f_m_t4.html#sec_fmt4_appendixc',1,'VII. Appendix C: Types of Indexes for Dataset Chunks']]],
  ['cache_24',['Cache',['../_t_n_m_d_c.html#adapt',1,'Adaptive Cache Resizing in the New Metadata Cache'],['../_t_n_m_d_c.html#configuring',1,'Configuring the New Metadata Cache'],['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_0_tune',1,'Fine-tuning the Metadata Cache'],['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_1_evict',1,'Metadata Cache Evict on Close -&amp;gt; Fine-tuning the Metadata Cache'],['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_1_cache',1,'Metadata Cache Image -&amp;gt; Fine-tuning the Metadata Cache *'],['../_t_n_m_d_c.html#oldnew',1,'Old and New Metadata Cache'],['../_t_n_m_d_c.html#new',1,'The New Metadata Cache'],['../_t_n_m_d_c.html#old',1,'The Old Metadata Cache'],['../hdf5_chunk_issues.html#sec_hdf5_chunk_issues_data',1,'The Raw Data Chunk Cache']]],
  ['cache_20configuration_25',['Cache Configuration',['../_t_n_m_d_c.html#defaults',1,'Default Metadata Cache Configuration'],['../_h5_a_c-cache-config-t.html',1,'Metadata Cache Configuration']]],
  ['cache_20control_26',['Cache Control',['../_h5_o__u_g.html#subsec_object_cache',1,'']]],
  ['cache_20debugging_20facilities_27',['New Metadata Cache Debugging Facilities',['../_t_n_m_d_c.html#news',1,'']]],
  ['cache_20efficiency_28',['Cache Efficiency',['../hdf5_chunk_issues.html#sec_hdf5_chunk_issues_effic',1,'']]],
  ['cache_20evict_20on_20close_20fine_20tuning_20the_20metadata_20cache_29',['Metadata Cache Evict on Close -&amp;gt; Fine-tuning the Metadata Cache',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_1_evict',1,'']]],
  ['cache_20image_20fine_20tuning_20the_20metadata_20cache_30',['Metadata Cache Image -&amp;gt; Fine-tuning the Metadata Cache *',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_1_cache',1,'']]],
  ['cache_20performance_31',['Assessing HDF5 Metadata Cache Performance',['../_performance.html#CB_MDCPerf',1,'']]],
  ['cache_20resizing_20in_20the_20new_20metadata_20cache_32',['Adaptive Cache Resizing in the New Metadata Cache',['../_t_n_m_d_c.html#adapt',1,'']]],
  ['cache_20size_33',['Cache Size',['../improve_compressed_perf.html#subsec_improve_compressed_perf_tune_cache',1,'Adjust Chunk Cache Size'],['../_t_n_m_d_c.html#decreasing',1,'Decreasing the Cache Size'],['../improve_compressed_perf.html#subsubsec_improve_compressed_perf_tune_cache_how',1,'How to Adjust the Chunk Cache Size'],['../_t_n_m_d_c.html#increasing',1,'Increasing the Cache Size']]],
  ['cache_20size_20and_20application_20memory_34',['Chunk Cache Size and Application Memory',['../improve_compressed_perf.html#subsubsec_improve_compressed_perf_tune_cache_mem',1,'']]],
  ['cache_20size_20decrease_20configuration_35',['Hit Rate Threshold Cache Size Decrease Configuration',['../_t_n_m_d_c.html#hrtcsdc',1,'']]],
  ['cache_20size_20decrease_20control_20fields_36',['Cache size decrease control fields',['../_h5_a_c-cache-config-t.html#csdcf',1,'']]],
  ['cache_20size_20from_20your_20program_37',['Controlling the New Metadata Cache Size From Your Program',['../_t_n_m_d_c.html#controlling',1,'']]],
  ['cache_20size_20increase_20configuration_38',['Cache Size Increase Configuration',['../_t_n_m_d_c.html#fcsic',1,'Flash Cache Size Increase Configuration'],['../_t_n_m_d_c.html#hrtcsic',1,'Hit Rate Threshold Cache Size Increase Configuration']]],
  ['cache_20size_20increase_20control_20fields_39',['Cache size increase control fields',['../_h5_a_c-cache-config-t.html#csicf',1,'']]],
  ['cache_20size_20increment_40',['Cache Size Increment',['../_t_n_m_d_c.html#fcsi',1,'Flash Cache Size Increment'],['../_t_n_m_d_c.html#hrtcsi',1,'Hit Rate Threshold Cache Size Increment']]],
  ['cache_20size_20reduction_41',['Cache Size Reduction',['../_t_n_m_d_c.html#acsr',1,'Ageout Cache Size Reduction'],['../_t_n_m_d_c.html#dacsr',1,'Ageout Cache Size Reduction'],['../_t_n_m_d_c.html#awhrtcsr',1,'Ageout With Hit Rate Threshold Cache Size Reduction'],['../_t_n_m_d_c.html#dawhrtcsr',1,'Ageout With Hit Rate Threshold Cache Size Reduction'],['../_t_n_m_d_c.html#hrtcsr',1,'Hit Rate Threshold Cache Size Reduction']]],
  ['cached_20data_42',['Flushing Cached Data',['../_v_f_l_t_n.html#subsec_vfl_data_flush',1,'']]],
  ['caching_43',['Chunk Caching',['../hdf5_chunking.html#sec_hdf5_chunking_cache',1,'']]],
  ['caching_20in_20hdf5_44',['Metadata Caching in HDF5',['../_t_n_m_d_c.html',1,'']]],
  ['call_20semantics_45',['C API Call Semantics',['../_h5_f_i_m__u_g.html#subsec_file_image_semantics',1,'']]],
  ['call_20substitutions_46',['Specific API Call Substitutions',['../_h5_v_l__u_g.html#subsubsec_vol_adapt_api',1,'']]],
  ['call_20syntax_47',['File Image C API Call Syntax',['../_h5_f_i_m__u_g.html#subsec_file_image_api',1,'']]],
  ['callback_48',['Optional Generic Callback',['../_v_o_l__connector.html#subsecVOLRefOpt',1,'']]],
  ['callback_20function_49',['Callback Function',['../copying_committed.html#subsec_copying_committed_datatypes_cb',1,'Callback Function'],['../_h5_e__u_g.html#subsubsec_error_ops_travers',1,'Traverse an Error Stack with a Callback Function']]],
  ['callback_20semantics_50',['File Image Callback Semantics',['../_h5_f_i_m__u_g.html#subsubsec_file_image_semantics_cbk',1,'']]],
  ['callback_20wrapper_20api_20calls_20for_20passthrough_20connector_20authors_51',['Appendix B Callback Wrapper API Calls for Passthrough Connector Authors',['../_v_o_l__connector.html#secVOLAppB',1,'']]],
  ['callbacks_52',['Callbacks',['../_v_o_l__connector.html#subsecVOLRefBlob',1,'Blob Callbacks'],['../_v_o_l__connector.html#subsecVOLRefConn',1,'Connector Information Callbacks'],['../_v_o_l__connector.html#subsecVOLRefDset',1,'Dataset Callbacks'],['../_v_o_l__connector.html#subsecVOLRefDType',1,'Datatype Callbacks'],['../_v_o_l__connector.html#subsecVOLRefFile',1,'File Callbacks'],['../_v_o_l__connector.html#subsecVOLFillIn',1,'Fill In VOL Callbacks'],['../_v_o_l__connector.html#subsecVOLRefGrp',1,'Group Callbacks'],['../_v_o_l__connector.html#subsecVOLRefIntrospect',1,'Introspection Callbacks'],['../_v_o_l__connector.html#subsecVOLRefLink',1,'Link Callbacks'],['../_v_o_l__connector.html#subsecVOLRefMap',1,'Mapping the API to the Callbacks'],['../_v_o_l__connector.html#subsecVOLRefObj',1,'Object Callbacks'],['../_v_o_l__connector.html#subsecVOLRefWrap',1,'Object Wrap Callbacks'],['../_v_o_l__connector.html#subsecVOLRefReq',1,'Request (Async) Callbacks'],['../_v_o_l__connector.html#subsecVOLRefAttr',1,'The Attribute Function Callbacks'],['../_v_o_l__connector.html#subsecVOLRefToken',1,'Token Callbacks']]],
  ['callbacks_20to_20hdf5_20api_20calls_53',['Appendix A Mapping of VOL Callbacks to HDF5 API Calls',['../_v_o_l__connector.html#secVOLAppA',1,'']]],
  ['calling_20requirements_20in_20parallel_20hdf5_20applications_54',['Collective Calling Requirements in Parallel HDF5 Applications',['../collective_calls.html',1,'']]],
  ['calls_55',['Calls',['../freeing_memory.html#sec_freeing_memory_api',1,'Affected API Calls'],['../_v_o_l__connector.html#secVOLAppA',1,'Appendix A Mapping of VOL Callbacks to HDF5 API Calls'],['../_h5_v_l__u_g.html#subsubsec_vol_connect_reg_calls',1,'Connector-Specific Registration Calls'],['../_h5_f_i_m__u_g.html#subsec_file_image_fort',1,'Fortran Signatures for File Image Operations API Calls'],['../_h5_f_i_m__u_g.html#subsec_file_image_java',1,'Java Signatures for File Image Operations API Calls'],['../_h5_v_l__u_g.html#subsubsec_vol_compat_native',1,'List of HDF5 Native VOL API Calls'],['../_h5_v_l__u_g.html#subsubsec_vol_compat_indep',1,'List of HDF5 VOL-Independent API Calls'],['../_h5_v_l__u_g.html#subsubsec_vol_adapt_native',1,'Protect Native-Only API Calls']]],
  ['calls_20for_20passthrough_20connector_20authors_56',['Appendix B Callback Wrapper API Calls for Passthrough Connector Authors',['../_v_o_l__connector.html#secVOLAppB',1,'']]],
  ['can_20i_20migrate_20my_20application_20if_20i_20still_20use_20the_20hdf5_201_206_20apis_57',['Can I migrate my application if I still use the HDF5 1.6 APIs?',['../rel_spec_110.html#subsubsec_rel_spec_110_migrate_faq_4',1,'']]],
  ['can_20i_20use_20the_20hdf5_20tools_20i_20use_20now_20to_20read_20files_20created_20with_20the_20new_20hdf5_201_2010_20features_58',['Can I use the HDF5 tools I use now to read files created with the new HDF5 1.10 features?',['../rel_spec_110.html#subsubsec_rel_spec_110_migrate_faq_6',1,'']]],
  ['cancel_59',['request: cancel',['../_v_o_l__connector.html#subsubsecVOLRefReqcancel',1,'']]],
  ['cancellation_20mechanisms_60',['Thread cancellation mechanisms',['../thread-safe-lib.html#subsec_tsafe_app_D',1,'']]],
  ['cancellation_20prevention_61',['Global structure and key for thread cancellation prevention',['../thread-safe-lib.html#subsec_tsafe_global_cancel',1,'']]],
  ['cancellation_20safety_62',['Thread Cancellation safety',['../thread-safe-lib.html#subsec_tsafe_impl_cancel',1,'']]],
  ['cancellation_20safety_63',['Test on cancellation safety',['../thread-safe-lib.html#subsec_tsafe_test_cancel',1,'']]],
  ['cannot_20be_20divided_64',['Variable-length datatypes cannot be divided',['../_l_b_datatypes.html#subsubsecLBDtypeSpecVLDiv',1,'']]],
  ['case_65',['Common Use Case',['../api-compat-macros.html#use-case',1,'']]],
  ['case_20study_66',['Case Study',['../improve_compressed_perf.html#sec_improve_compressed_perf_case',1,'']]],
  ['case_3a_20examining_20a_20jpss_20npp_20file_20with_20hdf5_20tools_67',['Use Case: Examining a JPSS NPP File With HDF5 Tools',['../_view_tools_j_p_s_s.html',1,'']]],
  ['case_3a_20java_20bindings_68',['CMake Presets Use Case: Java Bindings',['../cmake-presets.html#subsec_cmake_presets_build_java',1,'']]],
  ['case_3a_20parallel_20library_69',['CMake Presets Use Case: Parallel Library',['../cmake-presets.html#subsec_cmake_presets_build_par',1,'']]],
  ['case_3a_20s3_20on_20linux_70',['CMake Presets Use Case: S3 on linux',['../cmake-presets.html#subsec_cmake_presets_build_s3',1,'']]],
  ['case_3a_20static_20library_20and_20tools_71',['CMake Presets Use Case: Static Library and Tools',['../cmake-presets.html#subsec_cmake_presets_build_static',1,'']]],
  ['cases_72',['Use Cases',['../_r_e_l_v_e_r_s_i_o_n.html#sec_relver_use',1,'']]],
  ['caution_73',['A Word of Caution',['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_caution',1,'']]],
  ['caution_20when_20using_20custom_20filters_74',['A Word of Caution When Using Custom Filters',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_custom',1,'']]],
  ['caveats_20pitfalls_20and_20things_20to_20watch_20for_75',['Caveats, Pitfalls, and Things to Watch For',['../_u_n_i_c_o_d_e.html#sec_unicode_warn',1,'']]],
  ['certain_20options_76',['Arguments to Certain Options',['../_h5_t_o_o_l__r_p__u_g.html#subsubsec_cltools_h5repack_options_args',1,'']]],
  ['change_77',['Parallel Library Change',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_5_parchg',1,'']]],
  ['change_20a_20dataset_20s_20storage_20layout_78',['Change a Dataset&apos;s Storage Layout',['../_view_tools_edit.html#secViewToolsEditChange',1,'']]],
  ['change_20the_20access_20pattern_79',['Change the Access Pattern',['../improve_compressed_perf.html#subsec_improve_compressed_perf_tune_access',1,'']]],
  ['change_20the_20chunk_20size_80',['Change the Chunk Size',['../improve_compressed_perf.html#subsec_improve_compressed_perf_tune_size',1,'']]],
  ['changed_81',['Functions that changed',['../rel_spec_112.html#subsec_rel_spec_112_migrate_func',1,'']]],
  ['changed_20functions_82',['Changed Functions',['../rel_spec_18.html#subsubsec_rel_spec_18_change_9_new',1,'New and Changed Functions'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_4_new',1,'New and Changed Functions']]],
  ['changed_20functions_20and_20subroutines_83',['Changed Functions and Subroutines',['../rel_spec_18.html#subsubsec_rel_spec_18_change_11_new',1,'New and Changed Functions and Subroutines'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_10_new',1,'New and Changed Functions and Subroutines']]],
  ['changed_20functions_20classes_20subroutines_20wrappers_20and_20macros_84',['Changed Functions Classes Subroutines Wrappers and Macros',['../rel_spec_18.html#subsubsec_rel_spec_18_change_23_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_22_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_21_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_20_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_19_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_18_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_17_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_16_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_15_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_14_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_13_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_12_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_9versus8_func',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_8versus7_func',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_7versus6_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_6versus5_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_5versus4_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_2versus1_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_1versus0_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_6versus5_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_5versus4_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_4versus3_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_3versus2_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_2versus1_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_1versus0_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_0versus12_2_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros']]],
  ['changed_20library_20configuration_85',['Changed Library Configuration',['../rel_spec_18.html#subsubsec_rel_spec_18_change_1_config',1,'Changed Library Configuration'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_0_config',1,'Changed Library Configuration']]],
  ['changed_20output_3a_86',['Tools with changed output:',['../rel_spec_18.html#subsubsec_rel_spec_18_change_1_tools',1,'']]],
  ['changes_87',['Changes',['../rel_spec_114.html#subsec_rel_spec_114_migrate_api',1,'API Changes'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_8_conf',1,'Configure and Build Changes'],['../rel_spec_114.html#subsec_rel_spec_114_migrate_vfl',1,'Virtual File Layer (VFL) Changes'],['../rel_spec_114.html#subsec_rel_spec_114_migrate_vol',1,'Virtual Object Layer (VOL) Changes']]],
  ['changes_20between_20releases_88',['Changes between releases',['../rel_spec_2x_change.html#subsec_rel_spec_2x_bw_releases',1,'']]],
  ['changes_20for_20hdf5_201_2010_89',['Changes for HDF5 1 10',['../_f_m_t2.html#subsec_fmt2_intro_110',1,'I.B. Changes for HDF5 1.10'],['../_f_m_t3.html#subsec_fmt3_intro_110',1,'I.D. Changes for HDF5 1.10'],['../_f_m_t4.html#subsec_fmt4_intro_110',1,'I.D. Changes for HDF5 1.10'],['../rel_spec_110_change.html',1,'Release Software Changes for HDF5 1.10']]],
  ['changes_20for_20hdf5_201_2012_90',['Changes for HDF5 1 12',['../_f_m_t3.html#subsec_fmt3_intro_112',1,'I.C. Changes for HDF5 1.12'],['../_f_m_t4.html#subsec_fmt4_intro_112',1,'I.C. Changes for HDF5 1.12'],['../rel_spec_112_change.html',1,'Release Software Changes for HDF5 1.12']]],
  ['changes_20for_20hdf5_201_2014_91',['Release Software Changes for HDF5 1.14',['../rel_spec_114_change.html',1,'']]],
  ['changes_20for_20hdf5_202_200_92',['Changes for HDF5 2 0',['../_f_m_t3.html#subsec_fmt3_intro_20',1,'I.B. Changes for HDF5 2.0'],['../_f_m_t4.html#subsec_fmt4_intro_20',1,'I.B. Changes for HDF5 2.0']]],
  ['changes_20from_20release_20to_20release_20for_20hdf5_201_208_93',['Software Changes from Release to Release for HDF5-1.8',['../rel_spec_18.html#sec_rel_spec_18_change',1,'']]],
  ['changes_20from_20release_20to_20release_20in_20hdf5_201_2010_94',['Software Changes from Release to Release in HDF5 1.10',['../rel_spec_110_change.html#sec_rel_spec_110_change',1,'']]],
  ['changes_20from_20release_20to_20release_20in_20hdf5_201_2012_95',['Software Changes from Release to Release in HDF5 1.12',['../rel_spec_112_change.html#sec_rel_spec_112_change',1,'']]],
  ['changes_20from_20release_20to_20release_20in_20hdf5_201_2014_96',['Software Changes from Release to Release in HDF5 1.14',['../rel_spec_114_change.html#sec_rel_spec_114_change',1,'']]],
  ['changes_20from_20release_20to_20release_20in_20hdf5_202_20x_97',['Software Changes from Release to Release in HDF5 2.x',['../rel_spec_2x_change.html#sec_rel_spec_2x_change',1,'']]],
  ['changes_20to_20func_5fenter_98',['Changes to FUNC_ENTER',['../thread-safe-lib.html#subsec_tsafe_macro_fe',1,'']]],
  ['changes_20to_20hreturn_20and_20hreturn_5ferror_99',['Changes to HRETURN and HRETURN_ERROR',['../thread-safe-lib.html#subsec_tsafe_macro_ret',1,'']]],
  ['changes_20to_20macro_20expansions_100',['Changes to Macro expansions',['../thread-safe-lib.html#sec_tsafe_macro',1,'']]],
  ['changes_20to_20the_20file_20format_20specification_101',['Changes to the File Format Specification',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_0_form',1,'']]],
  ['changing_20the_20layout_20after_20dataset_20creation_102',['Changing the Layout after Dataset Creation',['../_l_b_dset_layout.html#secLBDsetLayoutChange',1,'']]],
  ['character_20datatypes_20in_20datasets_20and_20attributes_103',['Character Datatypes in Datasets and Attributes',['../_u_n_i_c_o_d_e.html#subsec_unicode_support_char',1,'']]],
  ['character_20string_20datatype_104',['Fixed Length 5-character String Datatype',['../_l_b_datatypes.html#subsecLBDtypeSpecStrFix',1,'']]],
  ['characters_20in_20utf_208_20and_20ascii_105',['Common Characters in UTF-8 and ASCII',['../_u_n_i_c_o_d_e.html#sec_unicode_common',1,'']]],
  ['check_20the_20compiler_20script_106',['Check the Compiler Script',['../_comp_t_s.html#subsubsec_compts_notapp_need_script',1,'']]],
  ['check_20the_20hdf5_20library’s_20binary_107',['Check the HDF5 Library’s Binary',['../_comp_t_s.html#subsubsec_compts_notapp_need_bin',1,'']]],
  ['checking_108',['Application Version Checking',['../_r_e_l_v_e_r_s_i_o_n.html#subsec_relver_use_app',1,'']]],
  ['chunk_109',['Writing by Chunk',['../_intro_par_chunk.html',1,'IntroParHDF5']]],
  ['chunk_20cache_110',['The Raw Data Chunk Cache',['../hdf5_chunk_issues.html#sec_hdf5_chunk_issues_data',1,'']]],
  ['chunk_20cache_20size_111',['Chunk Cache Size',['../improve_compressed_perf.html#subsec_improve_compressed_perf_tune_cache',1,'Adjust Chunk Cache Size'],['../improve_compressed_perf.html#subsubsec_improve_compressed_perf_tune_cache_how',1,'How to Adjust the Chunk Cache Size']]],
  ['chunk_20cache_20size_20and_20application_20memory_112',['Chunk Cache Size and Application Memory',['../improve_compressed_perf.html#subsubsec_improve_compressed_perf_tune_cache_mem',1,'']]],
  ['chunk_20caching_113',['Chunk Caching',['../hdf5_chunking.html#sec_hdf5_chunking_cache',1,'']]],
  ['chunk_20compression_114',['Chunk Compression',['../hdf5_chunk_issues.html#sec_hdf5_chunk_issues_comp',1,'']]],
  ['chunk_20index_115',['Chunk Index',['../_f_m_t3.html#subsec_fmt3_appendixc_chunk',1,'VII.A. The Single Chunk Index'],['../_f_m_t4.html#subsec_fmt4_appendixc_chunk',1,'VII.A. The Single Chunk Index']]],
  ['chunk_20maximum_20limits_116',['Chunk Maximum Limits',['../hdf5_chunking.html#sec_hdf5_chunking_limits',1,'']]],
  ['chunk_20options_117',['Partial Edge Chunk Options *',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_0_edge',1,'']]],
  ['chunk_20query_20functions_118',['Chunk Query Functions',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_5_chunk',1,'']]],
  ['chunk_20sharing_119',['Avoid chunk sharing',['../_par_compr.html#subsec_parcompr_perf_avoid',1,'']]],
  ['chunk_20size_120',['Change the Chunk Size',['../improve_compressed_perf.html#subsec_improve_compressed_perf_tune_size',1,'']]],
  ['chunk_20write_20function_121',['Chunk Write Function',['../_h5_d_o__u_g.html#sec_hldo_direct_chunk',1,'Direct Chunk Write Function'],['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_using',1,'Using the Direct Chunk Write Function']]],
  ['chunked_122',['Chunked',['../_l_b_dset_layout.html#subsecLBDsetLayoutChunk',1,'']]],
  ['chunked_20dataset_123',['Creating a Compressed and Chunked Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_compress',1,'']]],
  ['chunking_124',['Chunking',['../_l_b_dset_layout.html#susubsecLBDsetLayoutChunkProb',1,'Problems Using Chunking'],['../_l_b_dset_layout.html#susubsecLBDsetLayoutChunkWhy',1,'Why Chunking ?']]],
  ['chunking_20and_20compression_20in_20hdf5_125',['Chunking and Compression in HDF5',['../improve_compressed_perf.html#sec_improve_compressed_perf_chunk',1,'']]],
  ['chunking_20and_20partial_20i_20o_126',['Chunking and Partial I/O',['../hdf5_chunking.html#sec_hdf5_chunking_part',1,'']]],
  ['chunking_20in_20hdf5_127',['Chunking in HDF5',['../hdf5_chunking.html',1,'Chunking in HDF5'],['../improve_compressed_perf.html#subsec_improve_compressed_perf_chunk_chunk',1,'Chunking in HDF5']]],
  ['chunking_20issues_128',['Dataset Chunking Issues',['../hdf5_chunk_issues.html',1,'']]],
  ['chunking_20strategy_129',['Begin with a good chunking strategy',['../_par_compr.html#subsec_parcompr_perf_begin',1,'']]],
  ['chunks_130',['Chunks',['../_f_m_t3.html#sec_fmt3_appendixc',1,'VII. Appendix C: Types of Indexes for Dataset Chunks'],['../_f_m_t4.html#sec_fmt4_appendixc',1,'VII. Appendix C: Types of Indexes for Dataset Chunks'],['../hdf5_chunking.html#sec_hdf5_chunking_def',1,'What are Chunks?']]],
  ['chunks_20in_20the_20file_131',['Align chunks in the file',['../_par_compr.html#subsec_parcompr_perf_align',1,'']]],
  ['class_20mapping_132',['C API to C++ Class Mapping',['../h5_cpp_intro.html#cpp_mapping',1,'']]],
  ['classes_133',['Property List Classes',['../_h5_p__u_g.html#subsubsec_plist_class',1,'']]],
  ['classes_20and_20properties_134',['Datatype Classes and Properties',['../_h5_t__u_g.html#subsubsec_datatype_model_class',1,'']]],
  ['classes_20property_20lists_20and_20properties_135',['Property List Classes, Property Lists, and Properties',['../_h5_p__u_g.html#subsec_plist_class',1,'']]],
  ['classes_20subroutines_20wrappers_20and_20macros_136',['Classes Subroutines Wrappers and Macros',['../rel_spec_18.html#subsubsec_rel_spec_18_change_23_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_22_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_21_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_20_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_19_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_18_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_17_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_16_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_15_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_14_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_13_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_12_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_9versus8_func',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_8versus7_func',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_7versus6_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_6versus5_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_110_change.html#subsubsec_rel_spec_110_change_5versus4_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_2versus1_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_1versus0_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_6versus5_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_5versus4_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_4versus3_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_3versus2_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_2versus1_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_1versus0_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros'],['../rel_spec_114_change.html#subsubsec_rel_spec_114_change_0versus12_2_new',1,'New and Changed Functions, Classes, Subroutines, Wrappers, and Macros']]],
  ['clean_20up_20dimension_20scales_20when_20deleting_20a_20dataset_137',['Clean up Dimension Scales when deleting a Dataset',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_clean',1,'']]],
  ['clear_20an_20error_20stack_138',['Print and Clear an Error Stack',['../_h5_e__u_g.html#subsubsec_error_ops_print',1,'']]],
  ['close_139',['close',['../_v_o_l__connector.html#subsubsecVOLRefAttrclose',1,'attr: close'],['../_v_o_l__connector.html#subsubsecVOLRefDsetclose',1,'dataset: close'],['../_v_o_l__connector.html#subsubsecVOLRefDTypeclose',1,'datatype: close'],['../_v_o_l__connector.html#subsubsecVOLRefFileclose',1,'file: close'],['../_v_o_l__connector.html#subsubsecVOLRefGrpclose',1,'group: close']]],
  ['close_20fine_20tuning_20the_20metadata_20cache_140',['Metadata Cache Evict on Close -&amp;gt; Fine-tuning the Metadata Cache',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_1_evict',1,'']]],
  ['closing_20a_20file_141',['Closing a File',['../_h5_f__u_g.html#subsubsec_file_program_model_close',1,'']]],
  ['closing_20a_20group_142',['Closing a Group',['../_h5_g__u_g.html#subsubsec_group_program_close',1,'']]],
  ['closing_20an_20attribute_143',['Closing an Attribute',['../_h5_a__u_g.html#subsubsec_attribute_work_close',1,'']]],
  ['closing_20an_20hdf5_20file_144',['Closing an HDF5 File',['../_h5_f__u_g.html#subsec_file_closes',1,'']]],
  ['closing_20an_20object_145',['Closing an Object',['../_h5__u_g.html#subsubsec_program_model_close',1,'']]],
  ['closing_20files_146',['Closing Files',['../_v_f_l_t_n.html#subsec_vfl_imp_close',1,'Closing Files'],['../_h5_f__u_g.html#subsec_file_examples',1,'Code Examples for Opening and Closing Files']]],
  ['cmake_147',['CMake',['../cmake-presets.html#sec_cmake_presets_build',1,'Building HDF5 with CMake'],['../_l_b_compiling.html#secLBCompilingCMake',1,'Compiling an Application with CMake'],['../_l_b_compiling.html#subsecLBCompilingCMakeTroubless',1,'Troubleshooting CMake']]],
  ['cmake_20fetchcontent_148',['HDF5 Building and testing HDF5 VOL connectors with CMake FetchContent',['../_c_make_vols.html',1,'']]],
  ['cmake_20file_149',['Examine the hdf5-config.cmake File',['../_comp_t_s.html#subsubsec_compts_notapp_need_cmake',1,'']]],
  ['cmake_20presets_150',['CMake Presets',['../cmake-presets.html',1,'Building with CMake Presets'],['../cmake-presets.html#sec_cmake_presets_files',1,'CMake Presets']]],
  ['cmake_20presets_20use_20case_3a_20java_20bindings_151',['CMake Presets Use Case: Java Bindings',['../cmake-presets.html#subsec_cmake_presets_build_java',1,'']]],
  ['cmake_20presets_20use_20case_3a_20parallel_20library_152',['CMake Presets Use Case: Parallel Library',['../cmake-presets.html#subsec_cmake_presets_build_par',1,'']]],
  ['cmake_20presets_20use_20case_3a_20s3_20on_20linux_153',['CMake Presets Use Case: S3 on linux',['../cmake-presets.html#subsec_cmake_presets_build_s3',1,'']]],
  ['cmake_20presets_20use_20case_3a_20static_20library_20and_20tools_154',['CMake Presets Use Case: Static Library and Tools',['../cmake-presets.html#subsec_cmake_presets_build_static',1,'']]],
  ['cmake_20scripts_20for_20building_20applications_155',['CMake Scripts for Building Applications',['../_l_b_compiling.html#subsecLBCompilingCMakeScripts',1,'']]],
  ['cmake_20support_156',['Improvements to the CMake Support',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_6_cmake',1,'']]],
  ['cmakepresets_20json_157',['CMakePresets.json',['../cmake-presets.html#subsec_cmake_presets_files_json',1,'']]],
  ['cmakepresets_20json_20settings_158',['Default CMakePresets.json Settings',['../cmake-presets.html#subsec_cmake_presets_files_json_details',1,'']]],
  ['cmp_159',['cmp',['../_v_o_l__connector.html#subsubsecVOLRefConncmp',1,'info: cmp'],['../_v_o_l__connector.html#subsubsecVOLRefTokencmp',1,'token: cmp']]],
  ['code_160',['code',['../_h5_t_o_o_l__d_f__u_g.html#subsubsec_cltools_h5diff_exit',1,'Exit code'],['../thread-safe-lib.html#subsec_tsafe_app_A',1,'Recursive Lock implementation code']]],
  ['code_20conventions_161',['HDF5 Library Code Conventions',['../_c_o_d_e_c_o_n_v.html',1,'']]],
  ['code_20example_162',['A Complete Code Example',['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_example',1,'']]],
  ['code_20examples_163',['HDF5 Source Code Examples',['../_l_b_examples.html#secLBExamplesSrc',1,'']]],
  ['code_20examples_20for_20opening_20and_20closing_20files_164',['Code Examples for Opening and Closing Files',['../_h5_f__u_g.html#subsec_file_examples',1,'']]],
  ['code_20to_20load_20and_20use_20a_20vol_20connector_165',['If Needed: Update Your Code To Load And Use A VOL Connector',['../_h5_v_l__u_g.html#subsubsec_vol_quick_update',1,'']]],
  ['codes_166',['Macro expansion codes',['../thread-safe-lib.html#subsec_tsafe_app_E',1,'']]],
  ['collective_167',['Always collective',['../collective_calls.html#sec_collective_calls_func',1,'']]],
  ['collective_20calling_20requirements_20in_20parallel_20hdf5_20applications_168',['Collective Calling Requirements in Parallel HDF5 Applications',['../collective_calls.html',1,'']]],
  ['collective_20metadata_20i_20o_169',['Collective Metadata I O',['../collective_metadata_io.html',1,'Collective Metadata I/O'],['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_0_coll',1,'Collective Metadata I/O']]],
  ['collective_20metadata_20i_20o_20functions_170',['New Collective Metadata I/O Functions',['../collective_metadata_io.html#subsec_collective_metadata_io_apis_functions',1,'']]],
  ['collective_20metadata_20i_20o_20overview_171',['Collective Metadata I/O Overview',['../collective_metadata_io.html#sec_collective_metadata_io_overview',1,'']]],
  ['collective_20metadata_20i_20o_20user_20and_20resource_20documents_172',['Collective Metadata I/O User and Resource Documents',['../collective_metadata_io.html#sec_collective_metadata_io_resource',1,'']]],
  ['collective_20metadata_20operations_173',['Collective metadata operations',['../_par_compr.html#subsec_parcompr_perf_coll',1,'']]],
  ['collective_20unless_20target_20object_20will_20not_20be_20modified_174',['Collective, unless target object will not be modified',['../collective_calls.html#sec_collective_calls_nomod',1,'']]],
  ['collective_20vs_20independent_20i_20o_175',['Low-level collective vs. independent I/O',['../_par_compr.html#subsec_parcompr_perf_low',1,'']]],
  ['columns_20in_20c_176',['Writing Regularly Spaced Columns in C',['../_intro_par_regular_spaced.html#secIntroParRegularSpacedC',1,'']]],
  ['combinations_20of_20datatypes_177',['Complex Combinations of Datatypes',['../_h5_t__u_g.html#subsec_datatype_complex',1,'']]],
  ['command_20line_20tools_178',['Using VOL Connectors With The HDF5 Command-Line Tools',['../_h5_v_l__u_g.html#subsec_vol_cl',1,'']]],
  ['command_20line_20tools_179',['Command-line Tools',['../_view_tools_command.html',1,'']]],
  ['command_20line_20tools_20for_20converting_20hdf5_20files_180',['Command-line Tools For Converting HDF5 Files',['../_view_tools_convert.html',1,'']]],
  ['command_20line_20tools_20for_20editing_20hdf5_20files_181',['Command-line Tools For Editing HDF5 Files',['../_view_tools_edit.html',1,'']]],
  ['command_20line_20tools_20for_20hdf5_20files_182',['Command Line Tools for HDF5 Files',['../_command_tools.html',1,'Command Line Tools for HDF5 Files'],['../_u_g.html#sec_cltools',1,'Command Line Tools for HDF5 Files']]],
  ['command_20line_20tools_20for_20viewing_20hdf5_20files_183',['Command-line Tools For Viewing HDF5 Files',['../_view_tools_view.html',1,'']]],
  ['commands_184',['Creating Custom Commands',['../_about.html#custom_commands',1,'']]],
  ['comment_185',['Name: Object Comment',['../_f_m_t11.html#subsubsec_fmt11_dataobject_hdr_comment',1,'']]],
  ['comment_20message_186',['Comment Message',['../_f_m_t2.html#subsubsec_fmt2_dataobject_hdr_msg_comment',1,'IV.A.2.n. The Object Comment Message'],['../_f_m_t3.html#subsubsec_fmt3_dataobject_hdr_msg_comment',1,'IV.A.2.n. The Object Comment Message'],['../_f_m_t4.html#subsubsec_fmt4_dataobject_hdr_msg_comment',1,'IV.A.2.n. The Object Comment Message']]],
  ['comments_187',['Comments',['../rel_spec_18.html#subsubsec_rel_spec_18_change_23_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_22_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_21_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_20_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_19_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_18_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_15_compat',1,'Compatibility Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_14_compat',1,'Compatibility Report and Comments'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_0versus8_16_compat',1,'Compatibility Report and Comments'],['../_h5_o__u_g.html#subsec_object_comments',1,'Object Comments']]],
  ['commit_188',['datatype: commit',['../_v_o_l__connector.html#subsubsecVOLRefDTypecommit',1,'']]],
  ['committed_20datatypes_20with_20h5ocopy_189',['Committed Datatypes with H5Ocopy',['../copying_committed.html',1,'Copying Committed Datatypes with H5Ocopy'],['../copying_committed.html#sec_copying_committed_datatypes',1,'Copying Committed Datatypes with H5Ocopy']]],
  ['common_20characters_20in_20utf_208_20and_20ascii_190',['Common Characters in UTF-8 and ASCII',['../_u_n_i_c_o_d_e.html#sec_unicode_common',1,'']]],
  ['common_20use_20case_191',['Common Use Case',['../api-compat-macros.html#use-case',1,'']]],
  ['compact_192',['Compact',['../_l_b_dset_layout.html#subsecLBDsetLayoutCom',1,'Compact'],['../_f_m_t1.html#subsubsec_fmt1_dataobject_hdr_compact',1,'Name: Data Storage - Compact']]],
  ['comparison_193',['comparison',['../_h5_t_o_o_l__d_f__u_g.html#subsubsec_cltools_h5diff_file',1,'File comparison'],['../_h5_t_o_o_l__d_f__u_g.html#subsubsec_cltools_h5diff_object',1,'Object comparison']]],
  ['comparisons_194',['Compression Comparisons',['../_comp_t_s.html#subsec_compts_ineff_comp',1,'']]],
  ['compatibility_195',['Compatibility',['../rel_spec_110_change.html#subsec_rel_spec_110_change_0versus8_16_apicompat',1,'API Compatibility'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_0versus10_6_compat',1,'API Compatibility'],['../rel_spec_114_change.html#subsec_rel_spec_114_change_compat',1,'API Compatibility'],['../rel_spec_2x_change.html#subsec_rel_spec_2x_change_compat',1,'API Compatibility'],['../_h5_r__u_g.html#subsec_reference_compat',1,'API Compatibility'],['../_h5_v_l__u_g.html#subsec_vol_compat',1,'Compatibility'],['../_f_m_t3.html#subsec_fmt3_appendixd_encodedp',1,'VIII.C. Reference Encoding (Backward Compatibility)'],['../_f_m_t4.html#subsec_fmt4_appendixd_encodedp',1,'VIII.D. Reference Encoding (Backward Compatibility)']]],
  ['compatibility_20and_20new_20api_196',['Backward Compatibility and New API',['../_h5_r__u_g.html#subsubsec_reference_example_old',1,'']]],
  ['compatibility_20and_20performance_20issues_197',['Compatibility and Performance Issues',['../rel_spec_110_change.html#subsec_rel_spec_110_change_compatibility',1,'']]],
  ['compatibility_20for_20hdf5_201_208_20based_20applications_20accessing_20files_20created_20by_20hdf5_201_2010_202_20rfc_198',['Forward Compatibility for HDF5 1.8-based Applications Accessing Files Created by HDF5 1.10.2 ( RFC )',['../rel_spec_110.html#subsec_rel_spec_110_feat_new_2_compat',1,'']]],
  ['compatibility_20issues_199',['Compatibility Issues',['../api-compat-macros.html#compat-issues',1,'']]],
  ['compatibility_20macro_20mapping_20options_200',['Compatibility Macro Mapping Options',['../api-compat-macros.html#options',1,'']]],
  ['compatibility_20macros_201',['API Compatibility Macros',['../api-compat-macros.html',1,'']]],
  ['compatibility_20macros_20in_20hdf5_201_206_208_20and_20later_202',['Compatibility Macros in HDF5 1.6.8 and Later',['../api-compat-macros.html#macros',1,'']]],
  ['compatibility_20macros_20with_20associated_20renamed_20and_20new_20functions_203',['API Compatibility Macros with Associated Renamed and New Functions',['../rel_spec_18.html#subsubsec_rel_spec_18_change_0_compat',1,'']]],
  ['compatibility_20notes_20and_20report_204',['Compatibility Notes and Report',['../rel_spec_18.html#subsubsec_rel_spec_18_change_17_compat',1,'Compatibility Notes and Report'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_16_compat',1,'Compatibility Notes and Report'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_4versus3_compat',1,'Compatibility Notes and Report'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_2versus1_compat',1,'Compatibility Notes and Report'],['../rel_spec_112_change.html#subsubsec_rel_spec_112_change_1versus0_compat',1,'Compatibility Notes and Report']]],
  ['compatibility_20notes_20and_20report_20and_20comments_205',['Compatibility Notes and Report and Comments',['../rel_spec_18.html#subsubsec_rel_spec_18_change_23_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_22_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_21_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_20_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_19_compat',1,'Compatibility Notes and Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_18_compat',1,'Compatibility Notes and Report and Comments']]],
  ['compatibility_20notes_20and_20reports_206',['Compatibility Notes and Reports',['../rel_spec_110_change.html#subsec_rel_spec_110_change_9versus8_compat',1,'Compatibility Notes and Reports'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_8versus7_compat',1,'Compatibility Notes and Reports'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_7versus6_compat',1,'Compatibility Notes and Reports'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_6versus5_compat',1,'Compatibility Notes and Reports'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_5versus4_compat',1,'Compatibility Notes and Reports']]],
  ['compatibility_20report_207',['Compatibility Report',['../rel_spec_110_change.html#subsec_rel_spec_110_change_1versus0_compat',1,'']]],
  ['compatibility_20report_20and_20comments_208',['Compatibility Report and Comments',['../rel_spec_18.html#subsubsec_rel_spec_18_change_15_compat',1,'Compatibility Report and Comments'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_14_compat',1,'Compatibility Report and Comments'],['../rel_spec_110_change.html#subsec_rel_spec_110_change_0versus8_16_compat',1,'Compatibility Report and Comments']]],
  ['compatibility_20with_20other_20hdf5_20library_20versions_209',['Maintaining Compatibility with other HDF5 Library Versions',['../_accessibility.html#CB_MaintainCompat',1,'']]],
  ['compilation_210',['Library header files and conditional compilation',['../thread-safe-lib.html#sec_tsafe_compilation',1,'']]],
  ['compile_211',['How To Compile',['../_h_d_f5_examples.html#secHDF5ExamplesCompile',1,'']]],
  ['compile_20scripts_212',['Compile Scripts',['../_l_b_compiling.html#secLBCompilingLinux',1,'']]],
  ['compiler_20script_213',['Check the Compiler Script',['../_comp_t_s.html#subsubsec_compts_notapp_need_script',1,'']]],
  ['compiling_214',['Tools and Instructions on Compiling',['../_l_b_compiling.html#secLBCompiling',1,'']]],
  ['compiling_201_2010_20and_20earlier_20applications_20with_201_2012_215',['Compiling 1.10 and earlier applications with 1.12',['../rel_spec_112.html#subsec_rel_spec_112_migrate_compile',1,'']]],
  ['compiling_20an_20application_20with_20cmake_216',['Compiling an Application with CMake',['../_l_b_compiling.html#secLBCompilingCMake',1,'']]],
  ['compiling_20hdf5_20applications_217',['Compiling HDF5 Applications',['../_l_b_compiling.html',1,'LearnBasics']]],
  ['complete_20code_20example_218',['A Complete Code Example',['../_h5_d_o__u_g.html#subsec_hldo_direct_chunk_example',1,'']]],
  ['complex_20combinations_20of_20datatypes_219',['Complex Combinations of Datatypes',['../_h5_t__u_g.html#subsec_datatype_complex',1,'']]],
  ['complicated_20compound_20datatype_220',['Creating a Complicated Compound Datatype',['../_h5_t__u_g.html#subsubsec_datatype_complex_create',1,'']]],
  ['compound_221',['Compound',['../_l_b_datatypes.html#subsecLBDtypeSpecCmpd',1,'']]],
  ['compound_20dataset_222',['Creating a Table (Compound Dataset)',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_table',1,'']]],
  ['compound_20datatype_223',['Compound Datatype',['../_h5_t__u_g.html#subsubsec_datatype_complex_analyze',1,'Analyzing and Navigating a Compound Datatype'],['../_h5_t__u_g.html#subsubsec_datatype_complex_create',1,'Creating a Complicated Compound Datatype']]],
  ['compound_20datatypes_224',['Creating and Defining Compound Datatypes',['../_h5__u_g.html#subsubsec_program_model_compound',1,'']]],
  ['compound_20datatypes_225',['compound datatypes',['../_l_b_datatypes.html#subsubsecLBDtypeSpecCmpdDef',1,'Defining compound datatypes'],['../_l_b_datatypes.html#subsubsecLBDtypeSpecCmpdProp',1,'Properties of compound datatypes']]],
  ['compressed_20and_20chunked_20dataset_226',['Creating a Compressed and Chunked Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_compress',1,'']]],
  ['compressed_20data_227',['How to Use h5dump to Examine Files with Compressed Data',['../_comp_t_s.html#subsubsec_compts_notapp_tools_dump',1,'']]],
  ['compressed_20dataset_228',['Creating a Compressed Dataset',['../_l_b_com_dset.html#secLBComDsetCreate',1,'']]],
  ['compressed_20datasets_229',['Compressed Datasets',['../_l_b_com_dset.html',1,'Compressed Datasets'],['../improve_compressed_perf.html',1,'Improving I/O Performance When Working with HDF5 Compressed Datasets']]],
  ['compression_230',['Compression',['../_comp_t_s.html#subsec_compts_ineff_alt',1,'An Alternative to Compression'],['../hdf5_chunk_issues.html#sec_hdf5_chunk_issues_comp',1,'Chunk Compression'],['../_par_compr.html',1,'HDF5 Parallel Compression'],['../hdf5_chunking.html#sec_hdf5_chunking_filt',1,'I/O Filters and Compression']]],
  ['compression_20comparisons_231',['Compression Comparisons',['../_comp_t_s.html#subsec_compts_ineff_comp',1,'']]],
  ['compression_20filter_232',['Compression Filter',['../_comp_t_s.html#subsec_compts_notapp_miss',1,'How the HDF5 Library Configuration May Miss a Compression Filter'],['../_comp_t_s.html#subsec_compts_notapp_need',1,'How to Determine if the HDF5 Library was Configured with a Needed Compression Filter'],['../_comp_t_s.html#subsubsec_compts_notapp_tools_debug',1,'How to Use h5ls and h5debug to Find a Missing Compression Filter']]],
  ['compression_20filter_20to_20a_20dataset_233',['Apply Compression Filter to a Dataset',['../_view_tools_edit.html#secViewToolsEditApply',1,'']]],
  ['compression_20filter_20was_20not_20effective_234',['If a Compression Filter Was Not Effective',['../_comp_t_s.html#sec_compts_ineff',1,'']]],
  ['compression_20filters_235',['How to Use HDF5 Tools to Investigate Missing Compression Filters',['../_comp_t_s.html#subsec_compts_notapp_tools',1,'']]],
  ['compression_20in_20hdf5_236',['Compression in HDF5',['../improve_compressed_perf.html#sec_improve_compressed_perf_chunk',1,'Chunking and Compression in HDF5'],['../improve_compressed_perf.html#subsec_improve_compressed_perf_chunk_comp',1,'Compression in HDF5']]],
  ['compression_20troubleshooting_237',['Compression Troubleshooting',['../_comp_t_s.html#sec_compts_over',1,'An Overview of HDF5 Compression Troubleshooting'],['../_comp_t_s.html',1,'HDF5 Compression Troubleshooting']]],
  ['compression_20with_20hdf5_20parallel_20applications_238',['Using Compression with HDF5 Parallel Applications',['../rel_spec_110.html#subsubsec_rel_spec_110_feat_new_2_comp',1,'']]],
  ['conceptual_20model_239',['Conceptual model',['../_h5_d_s__u_g.html#sec_dim_scales_concept',1,'']]],
  ['concrete_20storage_20model_240',['Concrete Storage Model',['../_h5_d_m__u_g.html#subsubsec_data_model_storage_imple',1,'']]],
  ['conditional_20compilation_241',['Library header files and conditional compilation',['../thread-safe-lib.html#sec_tsafe_compilation',1,'']]],
  ['conditional_20inclusions_20or_20exclusions_20based_20on_20the_20version_242',['Conditional Inclusions or Exclusions Based on the Version',['../_r_e_l_v_e_r_s_i_o_n.html#subsec_relver_use_cond',1,'']]],
  ['conditions_243',['Conditions',['../_a_p_p_d_b_g.html#subsec_adddbg_intro_invar',1,'Invariant Conditions'],['../_a_p_p_d_b_g.html#sec_adddbg_invars',1,'Invariant Conditions']]],
  ['config_20cmake_20file_244',['Examine the hdf5-config.cmake File',['../_comp_t_s.html#subsubsec_compts_notapp_need_cmake',1,'']]],
  ['configuration_245',['Configuration',['../rel_spec_18.html#subsubsec_rel_spec_18_change_13_build',1,'Build and Configuration'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_12_build',1,'Build and Configuration'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_1_config',1,'Changed Library Configuration'],['../rel_spec_18.html#subsubsec_rel_spec_18_change_0_config',1,'Changed Library Configuration'],['../_t_n_m_d_c.html#decrement',1,'Decrement Configuration'],['../_t_n_m_d_c.html#defaults',1,'Default Metadata Cache Configuration'],['../_t_n_m_d_c.html#fcsic',1,'Flash Cache Size Increase Configuration'],['../_t_n_m_d_c.html#gconfig',1,'General Configuration'],['../_t_n_m_d_c.html#hrtcsdc',1,'Hit Rate Threshold Cache Size Decrease Configuration'],['../_t_n_m_d_c.html#hrtcsic',1,'Hit Rate Threshold Cache Size Increase Configuration'],['../_t_n_m_d_c.html#increment',1,'Increment Configuration'],['../_h5_a_c-cache-config-t.html',1,'Metadata Cache Configuration'],['../_t_n_m_d_c.html#parallel',1,'Parallel Configuration']]],
  ['configuration_20and_20large_20file_20support_246',['Autotools Configuration and Large File Support',['../rel_spec_110_change.html#subsec_rel_spec_110_change_0versus8_16_auto',1,'']]],
  ['configuration_20fields_247',['Parallel Configuration Fields',['../_h5_a_c-cache-config-t.html#pcf',1,'']]],
  ['configuration_20fields_248',['General configuration fields',['../_h5_a_c-cache-config-t.html#gcf',1,'']]],
  ['configuration_20file_249',['Configuration File',['../_h5_t_o_o_l__i_m__u_g.html#subsec_cltools_h5import_config',1,'']]],
  ['configuration_20may_20miss_20a_20compression_20filter_250',['How the HDF5 Library Configuration May Miss a Compression Filter',['../_comp_t_s.html#subsec_compts_notapp_miss',1,'']]],
  ['configure_20and_20build_20changes_251',['Configure and Build Changes',['../rel_spec_18.html#subsubsec_rel_spec_18_change_8_conf',1,'']]],
  ['configure_20option_252',['Configure option',['../_file_lock.html#subsec_filelock_disable_config',1,'']]],
  ['configure_20option_20and_20environment_20variable_253',['Configure Option and Environment Variable',['../_file_lock.html#subsec_filelock_feat_var',1,'']]],
  ['configured_20with_20a_20needed_20compression_20filter_254',['How to Determine if the HDF5 Library was Configured with a Needed Compression Filter',['../_comp_t_s.html#subsec_compts_notapp_need',1,'']]],
  ['configuring_20the_20new_20metadata_20cache_255',['Configuring the New Metadata Cache',['../_t_n_m_d_c.html#configuring',1,'']]],
  ['connector_256',['Connector',['../_v_o_l__connector.html#secVOLCreate',1,'Creating a New Connector'],['../_h5_v_l__u_g.html#subsubsec_vol_quick_set',1,'Determine How You Will Set The VOL Connector'],['../_h5_v_l__u_g.html#subsubsec_vol_quick_update',1,'If Needed: Update Your Code To Load And Use A VOL Connector'],['../_h5_v_l__u_g.html#subsubsec_vol_quick_read',1,'Read The Documentation For The New VOL Connector'],['../_v_o_l__connector.html#subsecVOLTest',1,'Testing Your Connector']]],
  ['connector_20author_20guide_257',['HDF5 Virtual Object Layer (VOL) Connector Author Guide',['../_v_o_l__connector.html',1,'']]],
  ['connector_20authors_258',['Appendix B Callback Wrapper API Calls for Passthrough Connector Authors',['../_v_o_l__connector.html#secVOLAppB',1,'']]],
  ['connector_20from_20git_259',['Example - Build and test HDF5 Asynchronous I/O VOL connector from GIT',['../_c_make_vols.html#subsec_cmakevols_build_ex',1,'']]],
  ['connector_20information_20callbacks_260',['Connector Information Callbacks',['../_v_o_l__connector.html#subsecVOLRefConn',1,'']]],
  ['connector_20interface_20reference_261',['VOL Connector Interface Reference',['../_v_o_l__connector.html#secVOLRef',1,'']]],
  ['connector_20is_20in_20the_20search_262',['If Using A Plugin: Make Sure The VOL Connector Is In The Search',['../_h5_v_l__u_g.html#subsubsec_vol_quick_plugin',1,'']]],
  ['connector_20optional_20values_20by_20subclass_263',['Appendix C Native VOL Connector Optional Values By Subclass',['../_v_o_l__connector.html#secVOLAppC',1,'']]],
  ['connector_20search_20path_264',['VOL Connector Search Path',['../_h5_v_l__u_g.html#subsubsec_vol_connect_search',1,'']]],
  ['connector_20specific_20registration_20calls_265',['Connector-Specific Registration Calls',['../_h5_v_l__u_g.html#subsubsec_vol_connect_reg_calls',1,'']]],
  ['connector_20use_266',['Connector Use',['../_h5_v_l__u_g.html#subsec_vol_use',1,'']]],
  ['connector_20versioning_267',['Connector Versioning',['../_h5_v_l__u_g.html#subsubsec_vol_connect_version',1,'']]],
  ['connector_20via_20the_20environment_20variable_268',['Optional: Set The VOL Connector Via The Environment Variable',['../_h5_v_l__u_g.html#subsubsec_vol_quick_opt',1,'']]],
  ['connectors_269',['Connectors',['../_v_o_l__connector.html#subsecVOLPassthrough',1,'Passthrough Connectors'],['../_h5_v_l__u_g.html#subsec_vol_connect',1,'VOL Connectors']]],
  ['connectors_20with_20cmake_20fetchcontent_270',['HDF5 Building and testing HDF5 VOL connectors with CMake FetchContent',['../_c_make_vols.html',1,'']]],
  ['connectors_20with_20the_20hdf5_20command_20line_20tools_271',['Using VOL Connectors With The HDF5 Command-Line Tools',['../_h5_v_l__u_g.html#subsec_vol_cl',1,'']]],
  ['considerations_272',['Considerations',['../_par_compr.html#sec_parcompr_perf',1,'Performance Considerations'],['../_h5_f_d__u_g.html#subsec_vfd_performance',1,'Performance Considerations']]],
  ['consistency_20and_20correlation_20of_20image_20and_20palette_20attributes_273',['Consistency and Correlation of Image and Palette Attributes',['../_i_m_g.html#sec_tab_spec_sect3',1,'']]],
  ['constants_20and_20enumerated_20types_274',['Constants and Enumerated Types',['../_h_d_f5_c_o_n_s_t.html',1,'']]],
  ['construct_20and_20read_20a_20data_20packet_275',['Using HDF5 to Construct and Read a Data Packet',['../_h5_f_i_m__u_g.html#subsubsec_file_image_example_dp',1,'']]],
  ['construction_276',['In-memory HDF5 File Image Construction',['../_h5_f_i_m__u_g.html#subsubsec_file_image_example_const',1,'']]],
  ['content_20and_20structure_277',['File Content and Structure',['../_view_tools_view.html#secViewToolsViewContent',1,'']]],
  ['contents_278',['Contents',['../_view_tools_view.html#secViewToolsViewTOC',1,'Contents'],['../_view_tools_edit.html#secViewToolsEditTOC',1,'Contents'],['../_view_tools_convert.html#secViewToolsConvertTOC',1,'Contents'],['../_view_tools_j_p_s_s.html#secViewToolsJPSSTOC',1,'Contents'],['../_view_tools_j_p_s_s.html#secViewToolsJPSSDeter',1,'Determining File Contents'],['../_l_b_file_create.html#subsecLBFileExampleCont',1,'File Contents'],['../_l_b_dset_create.html#subsecLBDsetCreateContent',1,'File Contents'],['../_l_b_dset_r_w.html#secLBDsetRWExCont',1,'File Contents'],['../_l_b_attr_create.html#secLBAttrCreateRWExCont',1,'File Contents'],['../_l_b_grp_create.html#secLBGrpCreateRWExCont',1,'File Contents'],['../_l_b_grp_create_names.html#secLBGrpCreateNamesExCont',1,'File Contents'],['../_l_b_grp_dset.html#secLBGrpDsetExCont',1,'File Contents']]],
  ['contents_20of_20an_20hdf5_20file_279',['Discovering the Contents of an HDF5 File',['../_l_b_contents.html',1,'LearnBasics']]],
  ['contiguous_280',['Contiguous',['../_l_b_dset_layout.html#subsecLBDsetLayoutCont',1,'']]],
  ['contiguous_20dataset_281',['Creating a New HDF5 File with a Contiguous Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_file',1,'']]],
  ['contiguous_20hyperslab_282',['Writing by Contiguous Hyperslab',['../_intro_par_cont_hyperslab.html',1,'IntroParHDF5']]],
  ['contiguous_20hyperslab_20in_20c_283',['Writing a Contiguous Hyperslab in C',['../_intro_par_cont_hyperslab.html#secIntroParContHyperslabC',1,'']]],
  ['contiguous_20hyperslab_20in_20fortran_284',['Writing a Contiguous Hyperslab in Fortran',['../_intro_par_cont_hyperslab.html#secIntroParContHyperslabFort',1,'']]],
  ['contiguous_20i_20o_20functions_285',['Contiguous I/O Functions',['../_v_f_l_t_n.html#subsec_vfl_data_cont',1,'']]],
  ['continuation_286',['Continuation',['../_f_m_t1.html#subsubsec_fmt1_dataobject_hdr_continuation',1,'Name: Object Header Continuation'],['../_f_m_t11.html#subsubsec_fmt11_dataobject_hdr_continuation',1,'Name: Object Header Continuation']]],
  ['continuation_20message_287',['Continuation Message',['../_f_m_t2.html#subsubsec_fmt2_dataobject_hdr_msg_continuation',1,'IV.A.2.q. The Object Header Continuation Message'],['../_f_m_t3.html#subsubsec_fmt3_dataobject_hdr_msg_continuation',1,'IV.A.2.q. The Object Header Continuation Message'],['../_f_m_t4.html#subsubsec_fmt4_dataobject_hdr_msg_continuation',1,'IV.A.2.q. The Object Header Continuation Message']]],
  ['control_288',['Cache Control',['../_h5_o__u_g.html#subsec_object_cache',1,'']]],
  ['control_20fields_289',['control fields',['../_h5_a_c-cache-config-t.html#csdcf',1,'Cache size decrease control fields'],['../_h5_a_c-cache-config-t.html#csicf',1,'Cache size increase control fields']]],
  ['controlling_20the_20new_20metadata_20cache_20size_20from_20your_20program_290',['Controlling the New Metadata Cache Size From Your Program',['../_t_n_m_d_c.html#controlling',1,'']]],
  ['conventions_291',['Conventions',['../_c_o_d_e_c_o_n_v.html',1,'HDF5 Library Code Conventions'],['../_h5_t_o_o_l__d_p__u_g.html#subsubsec_cltools_h5dump_options_args',1,'Option Argument Conventions']]],
  ['conversion_292',['Java Array Conversion',['../_h_d_f_a_r_r_a_y.html',1,'']]],
  ['conversion_20and_20selection_293',['Data Transfer: Datatype Conversion and Selection',['../_h5_t__u_g.html#subsec_datatype_transfer',1,'']]],
  ['conversion_20to_20and_20from_294',['Text Descriptions of Datatypes: Conversion to and from',['../_h5_t__u_g.html#subsec_datatype_text',1,'']]],
  ['converting_20hdf5_20files_295',['Command-line Tools For Converting HDF5 Files',['../_view_tools_convert.html',1,'']]],
  ['cookbook_296',['Cookbook',['../_cookbook.html',1,'']]],
  ['copy_297',['copy',['../_v_o_l__connector.html#subsubsecVOLRefConncopy',1,'info: copy'],['../_v_o_l__connector.html#subsubsecVOLRefLinkcopy',1,'link: copy'],['../_v_o_l__connector.html#subsubsecVOLRefObjcopy',1,'object: copy']]],
  ['copy_20objects_20to_20another_20file_298',['Copy Objects to Another File',['../_view_tools_edit.html#secViewToolsEditCopy',1,'']]],
  ['copying_20committed_20datatypes_20with_20h5ocopy_299',['Copying Committed Datatypes with H5Ocopy',['../copying_committed.html',1,'Copying Committed Datatypes with H5Ocopy'],['../copying_committed.html#sec_copying_committed_datatypes',1,'Copying Committed Datatypes with H5Ocopy']]],
  ['core_20driver_300',['The Memory (aka Core) Driver',['../_h5_f__u_g.html#subsubsec_file_alternate_drivers_mem',1,'']]],
  ['core_20topics_301',['Core Topics',['../_l_b_training.html#autotoc_md11',1,'']]],
  ['core_20vfd_20tracks_20file_20modifications_302',['How the Core VFD Tracks File Modifications',['../mod_region_writes.html#subsec_mod_region_writes_intro_how',1,'']]],
  ['core_5fmenu_303',['core_menu',['../md_docs_2doxygen_2examples_2menus_2core__menu.html',1,'']]],
  ['correct_20c_20run‐time_20everywhere_304',['Use the Same Memory Manager/Correct C Run‐time Everywhere',['../freeing_memory.html#subsec_freeing_memory_mitigation1',1,'']]],
  ['correlation_20of_20image_20and_20palette_20attributes_305',['Consistency and Correlation of Image and Palette Attributes',['../_i_m_g.html#sec_tab_spec_sect3',1,'']]],
  ['count_20message_306',['Count Message',['../_f_m_t2.html#subsubsec_fmt2_dataobject_hdr_msg_refcount',1,'IV.A.2.w. The Object Reference Count Message'],['../_f_m_t3.html#subsubsec_fmt3_dataobject_hdr_msg_refcount',1,'IV.A.2.w. The Object Reference Count Message'],['../_f_m_t4.html#subsubsec_fmt4_dataobject_hdr_msg_refcount',1,'IV.A.2.w. The Object Reference Count Message']]],
  ['counting_307',['Counting',['../_h5_i__u_g.html#subsec_identifier_refcount',1,'Reference Counting'],['../_h5_o__u_g.html#subsec_object_refcount',1,'Reference Counting']]],
  ['covered_308',['Topics Covered',['../_learn_h_d_f_view.html#subsec_learn_hv_begin_topics',1,'']]],
  ['create_309',['create',['../_v_o_l__connector.html#subsubsecVOLRefAttrcreate',1,'attr: create'],['../_v_o_l__connector.html#subsubsecVOLRefDsetcreate',1,'dataset: create'],['../_v_o_l__connector.html#subsubsecVOLRefFilecreate',1,'file: create'],['../_v_o_l__connector.html#subsubsecVOLRefGrpcreate',1,'group: create'],['../_v_o_l__connector.html#subsubsecVOLRefLinkcreate',1,'link: create']]],
  ['create_20a_20dataset_310',['Steps to Create a Dataset',['../_l_b_dset_create.html#secLBDsetCreateSteps',1,'']]],
  ['create_20a_20dataset_311',['Steps to create a dataset',['../_intro_h_d_f5.html#subsec_intro_pm_dataset',1,'']]],
  ['create_20a_20file_312',['Steps to create a file',['../_intro_h_d_f5.html#subsec_intro_pm_file',1,'']]],
  ['create_20a_20group_313',['Steps to create a group',['../_intro_h_d_f5.html#subsec_intro_pm_group',1,'']]],
  ['create_20a_20label_20for_20a_20dimension_314',['Create a label for a dimension',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_label',1,'']]],
  ['create_20and_20write_315',['Data set create and write',['../thread-safe-lib.html#subsec_tsafe_test_create',1,'']]],
  ['create_20and_20write_20to_20an_20attribute_316',['Steps to create and write to an attribute',['../_intro_h_d_f5.html#subsec_intro_pm_attr',1,'']]],
  ['create_20dataset_317',['Create Dataset',['../_h5_d__u_g.html#subsubsec_dataset_program_create',1,'']]],
  ['create_20new_20dimension_20scale_20with_20initial_20values_318',['Create new Dimension Scale with Initial Values',['../_h5_d_s__u_g.html#subsubsec_dim_scales_api_model_create',1,'']]],
  ['created_20by_20an_20application_20rebuilt_20with_20hdf5_201_2010_319',['Will my old software read files created by an application rebuilt with HDF5 1.10?',['../rel_spec_110.html#subsubsec_rel_spec_110_migrate_faq_5',1,'']]],
  ['created_20by_20hdf5_201_2010_202_20rfc_320',['Forward Compatibility for HDF5 1.8-based Applications Accessing Files Created by HDF5 1.10.2 ( RFC )',['../rel_spec_110.html#subsec_rel_spec_110_feat_new_2_compat',1,'']]],
  ['created_20with_20the_20new_20hdf5_201_2010_20features_321',['Can I use the HDF5 tools I use now to read files created with the new HDF5 1.10 features?',['../rel_spec_110.html#subsubsec_rel_spec_110_migrate_faq_6',1,'']]],
  ['creating_20a_20complicated_20compound_20datatype_322',['Creating a Complicated Compound Datatype',['../_h5_t__u_g.html#subsubsec_datatype_complex_create',1,'']]],
  ['creating_20a_20compressed_20and_20chunked_20dataset_323',['Creating a Compressed and Chunked Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_compress',1,'']]],
  ['creating_20a_20compressed_20dataset_324',['Creating a Compressed Dataset',['../_l_b_com_dset.html#secLBComDsetCreate',1,'']]],
  ['creating_20a_20dataset_325',['Creating a Dataset',['../_l_b_dset_create.html',1,'LearnBasics']]],
  ['creating_20a_20dataset_20in_20a_20specific_20group_326',['Creating a Dataset in a Specific Group',['../_h5_g__u_g.html#subsubsec_group_program_dataset',1,'']]],
  ['creating_20a_20group_327',['Creating a Group',['../_h5_g__u_g.html#subsubsec_group_program_create',1,'']]],
  ['creating_20a_20new_20connector_328',['Creating a New Connector',['../_v_o_l__connector.html#secVOLCreate',1,'']]],
  ['creating_20a_20new_20file_329',['Creating a New File',['../_h5_f__u_g.html#subsubsec_file_program_model_create',1,'']]],
  ['creating_20a_20new_20hdf5_20file_20with_20a_20contiguous_20dataset_330',['Creating a New HDF5 File with a Contiguous Dataset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_file',1,'']]],
  ['creating_20a_20new_20reference_20manual_20entry_331',['Creating a New Reference Manual Entry',['../_about.html#new_rm_entry',1,'']]],
  ['creating_20a_20property_20list_332',['Creating a Property List',['../_h5_f__u_g.html#subsubsec_file_property_lists_create',1,'']]],
  ['creating_20a_20table_20compound_20dataset_333',['Creating a Table (Compound Dataset)',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_table',1,'']]],
  ['creating_20an_20attribute_334',['Creating an Attribute',['../_l_b_attr_create.html',1,'LearnBasics']]],
  ['creating_20an_20attribute_335',['Creating an attribute',['../_l_b_attr_create.html#secLBAttrCreate',1,'']]],
  ['creating_20an_20extendible_20dataset_336',['Creating an Extendible Dataset',['../_l_b_ext_dset.html#secLBExtDsetCreate',1,'']]],
  ['creating_20an_20group_337',['Creating an Group',['../_l_b_grp_create.html',1,'LearnBasics']]],
  ['creating_20an_20group_338',['Creating an group',['../_l_b_grp_create.html#secLBGrpCreate',1,'']]],
  ['creating_20an_20hdf5_20file_339',['Creating an HDF5 File',['../_l_b_file_create.html',1,'Creating an HDF5 File'],['../_h5__u_g.html#subsubsec_program_model_create',1,'Creating an HDF5 File']]],
  ['creating_20an_20hdf5_20file_20user_20block_340',['Creating an HDF5 File User Block',['../_files.html#CB_UserBlock',1,'']]],
  ['creating_20an_20hdf5_20filter_20plugin_341',['Creating an HDF5 Filter Plugin',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_prog_create',1,'']]],
  ['creating_20an_20image_20and_20a_20subset_342',['Creating an Image and a Subset',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_subset',1,'']]],
  ['creating_20and_20accessing_20a_20dataset_20with_20phdf5_343',['Creating and Accessing a Dataset with PHDF5',['../_intro_par_h_d_f5.html#subsec_pintro_create_dset',1,'']]],
  ['creating_20and_20accessing_20a_20file_20with_20phdf5_344',['Creating and Accessing a File with PHDF5',['../_intro_par_h_d_f5.html#subsec_pintro_create_file',1,'']]],
  ['creating_20and_20defining_20compound_20datatypes_345',['Creating and Defining Compound Datatypes',['../_h5__u_g.html#subsubsec_program_model_compound',1,'']]],
  ['creating_20and_20initializing_20a_20dataset_346',['Creating and Initializing a Dataset',['../_h5__u_g.html#subsubsec_program_model_dset',1,'']]],
  ['creating_20and_20opening_20files_347',['Creating and Opening Files',['../_v_f_l_t_n.html#subsec_vfl_use_create',1,'']]],
  ['creating_20and_20using_20user‐defined_20datatypes_348',['Creating and Using User‐defined Datatypes',['../_h5_t__u_g.html#subsubsec_datatype_usage_user',1,'']]],
  ['creating_20and_20working_20with_20groups_349',['Creating and Working with Groups',['../_h5__u_g.html#subsubsec_program_model_group',1,'']]],
  ['creating_20and_20writing_20a_20dataset_350',['Applying a Third-party Filter When Creating and Writing a Dataset',['../_h5_p_l__u_g.html#sssec_filt_pl_model_apply',1,'']]],
  ['creating_20and_20writing_20extendable_20datasets_351',['Creating and Writing Extendable Datasets',['../_h5__u_g.html#subsubsec_program_model_extend',1,'']]],
  ['creating_20attributes_352',['Creating Attributes',['../_learn_h_d_f_view.html#subsec_learn_hv_topics_attr',1,'']]],
  ['creating_20custom_20commands_353',['Creating Custom Commands',['../_about.html#custom_commands',1,'']]],
  ['creating_20datasets_20in_20groups_354',['Creating Datasets in Groups',['../_l_b_grp_dset.html',1,'LearnBasics']]],
  ['creating_20groups_20using_20absolute_20and_20relative_20names_355',['Creating Groups using Absolute and Relative Names',['../_l_b_grp_create_names.html',1,'LearnBasics']]],
  ['creating_20large_20hdf5_20attributes_356',['Creating &quot;Large&quot; HDF5 Attributes',['../_attributes.html#CB_LargeAttributes',1,'']]],
  ['creating_20links_357',['Creating Links',['../_h5_g__u_g.html#subsubsec_group_program_links',1,'Creating Links'],['../_h5_l__u_g.html#subsec_link_create',1,'Creating Links']]],
  ['creating_20or_20opening_20an_20hdf5_20file_358',['Creating or Opening an HDF5 File',['../_h5_f__u_g.html#subsec_file_create',1,'']]],
  ['creating_20references_20to_20regions_359',['Creating References to Regions',['../_h5_s__u_g.html#subsubsec_dataspace_refer_create',1,'Creating References to Regions'],['../_h5_s__u_g.html#subsubsec_dataspace_deprecated_refer_create',1,'Deprecated Creating References to Regions']]],
  ['creating_20writing_20and_20reading_20attributes_360',['Creating, Writing, and Reading Attributes',['../_h5_a__u_g.html#subsubsec_attribute_work_create',1,'']]],
  ['creation_361',['Creation',['../_l_b_dset_layout.html#secLBDsetLayoutChange',1,'Changing the Layout after Dataset Creation'],['../_h5_t__u_g.html#subsubsec_datatype_usage_create',1,'Dataset Creation']]],
  ['creation_362',['Test on attribute creation',['../thread-safe-lib.html#subsec_tsafe_test_attr',1,'']]],
  ['creation_20and_20file_20access_20properties_363',['File Creation and File Access Properties',['../_h5_f__u_g.html#subsec_file_creation_access',1,'']]],
  ['creation_20properties_364',['File Creation Properties',['../_h5_f__u_g.html#subsubsec_file_property_lists_props',1,'']]],
  ['creation_20property_20list_365',['Example with the File Creation Property List',['../_h5_f__u_g.html#subsubsec_file_examples_props',1,'']]],
  ['cross_20platform_20portability_366',['Cross-platform Portability',['../_u_n_i_c_o_d_e.html#subsec_unicode_warn_port',1,'']]],
  ['crt_367',['The Windows C Run-time (CRT)',['../freeing_memory.html#sec_freeing_memory_crt',1,'']]],
  ['custom_20commands_368',['Creating Custom Commands',['../_about.html#custom_commands',1,'']]],
  ['custom_20file_20drivers_369',['Custom File Drivers',['../_h5_f_d__u_g.html#subsec_vfd_custom',1,'']]],
  ['custom_20filters_370',['Custom Filters',['../_h5_p_l__u_g.html#subsubsec_filter_plugins_model_custom',1,'A Word of Caution When Using Custom Filters'],['../_h5_z__u_g.html#subsec_filter_custom',1,'Custom Filters']]],
  ['customized_20printing_20of_20an_20error_20stack_371',['Customized Printing of an Error Stack',['../_h5_e__u_g.html#subsubsec_error_ops_custom_print',1,'']]],
  ['cycle_372',['Map Object Life Cycle',['../_h5_m__u_g.html#subsec_map_lifecycle',1,'']]],
  ['cycle_20of_20the_20datatype_20object_373',['Life Cycle of the Datatype Object',['../_h5_t__u_g.html#subsec_datatype_life',1,'']]]
];
