Opened "TEST.h5" with sec2 driver.
Monitoring dataset /DSET_TWO...
dimension 0: 4->6 (increases)
dimension 1: 10->12 (increases)
dimension 0: 6->8 (increases)
dimension 1: 12->1 (decreases)
dimension 0: 8->10 (increases)
dimension 1: 1->1 (unchanged)
dimension 0: 10->3 (decreases)
dimension 1: 1->3 (increases)
dimension 0: 3->2 (decreases)
dimension 1: 3->2 (decreases)
dimension 0: 2->1 (decreases)
dimension 1: 2->2 (unchanged)
dimension 0: 1->1 (unchanged)
dimension 1: 2->4 (increases)
dimension 0: 1->1 (unchanged)
dimension 1: 4->3 (decreases)
