// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * typedef H5T_conv_ret_t (*H5T_conv_except_func_t)(H5T_conv_except_t, hid_t, hid_t, void *, void *, void *)
 * }
 */
public class H5T_conv_except_func_t {

    H5T_conv_except_func_t()
    {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(int except_type, long src_id, long dst_id, MemorySegment src_buf, MemorySegment dst_buf,
                  MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC =
        FunctionDescriptor.of(hdf5_h.C_INT, hdf5_h.C_INT, hdf5_h.C_LONG, hdf5_h.C_LONG, hdf5_h.C_POINTER,
                              hdf5_h.C_POINTER, hdf5_h.C_POINTER);

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() { return $DESC; }

    private static final MethodHandle UP$MH =
        hdf5_h.upcallHandle(H5T_conv_except_func_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(H5T_conv_except_func_t.Function fi, Arena arena)
    {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, int except_type, long src_id, long dst_id,
                             MemorySegment src_buf, MemorySegment dst_buf, MemorySegment user_data)
    {
        try {
            return (int)DOWN$MH.invokeExact(funcPtr, except_type, src_id, dst_id, src_buf, dst_buf,
                                            user_data);
        }
        catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
