// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * struct H5VL_link_specific_args_t {
 *     H5VL_link_specific_t op_type;
 *     union {
 *         struct {
 *             hbool_t *exists;
 *         } exists;
 *         H5VL_link_iterate_args_t iterate;
 *     } args;
 * }
 * }
 */
public class H5VL_link_specific_args_t {

    H5VL_link_specific_args_t()
    {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT =
        MemoryLayout
            .structLayout(hdf5_h.C_INT.withName("op_type"), MemoryLayout.paddingLayout(4),
                          H5VL_link_specific_args_t.args.layout().withName("args"))
            .withName("H5VL_link_specific_args_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() { return $LAYOUT; }

    private static final OfInt op_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("op_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5VL_link_specific_t op_type
     * }
     */
    public static final OfInt op_type$layout() { return op_type$LAYOUT; }

    private static final long op_type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5VL_link_specific_t op_type
     * }
     */
    public static final long op_type$offset() { return op_type$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5VL_link_specific_t op_type
     * }
     */
    public static int op_type(MemorySegment struct) { return struct.get(op_type$LAYOUT, op_type$OFFSET); }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5VL_link_specific_t op_type
     * }
     */
    public static void op_type(MemorySegment struct, int fieldValue)
    {
        struct.set(op_type$LAYOUT, op_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hbool_t *exists;
     *     } exists;
     *     H5VL_link_iterate_args_t iterate;
     * }
     * }
     */
    public static class args {

        args()
        {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT =
            MemoryLayout
                .unionLayout(H5VL_link_specific_args_t.args.exists.layout().withName("exists"),
                             H5VL_link_iterate_args_t.layout().withName("iterate"))
                .withName("$anon$657:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() { return $LAYOUT; }

        /**
         * {@snippet lang=c :
         * struct {
         *     hbool_t *exists;
         * }
         * }
         */
        public static class exists {

            exists()
            {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT =
                MemoryLayout.structLayout(hdf5_h.C_POINTER.withName("exists")).withName("$anon$662:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() { return $LAYOUT; }

            private static final AddressLayout exists$LAYOUT =
                (AddressLayout)$LAYOUT.select(groupElement("exists"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * hbool_t *exists
             * }
             */
            public static final AddressLayout exists$layout() { return exists$LAYOUT; }

            private static final long exists$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * hbool_t *exists
             * }
             */
            public static final long exists$offset() { return exists$OFFSET; }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * hbool_t *exists
             * }
             */
            public static MemorySegment exists(MemorySegment struct)
            {
                return struct.get(exists$LAYOUT, exists$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * hbool_t *exists
             * }
             */
            public static void exists(MemorySegment struct, MemorySegment fieldValue)
            {
                struct.set(exists$LAYOUT, exists$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index)
            {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator)
            {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
            {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                    Consumer<MemorySegment> cleanup)
            {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout exists$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("exists"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     hbool_t *exists;
         * } exists
         * }
         */
        public static final GroupLayout exists$layout() { return exists$LAYOUT; }

        private static final long exists$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     hbool_t *exists;
         * } exists
         * }
         */
        public static final long exists$offset() { return exists$OFFSET; }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     hbool_t *exists;
         * } exists
         * }
         */
        public static MemorySegment exists(MemorySegment union)
        {
            return union.asSlice(exists$OFFSET, exists$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     hbool_t *exists;
         * } exists
         * }
         */
        public static void exists(MemorySegment union, MemorySegment fieldValue)
        {
            MemorySegment.copy(fieldValue, 0L, union, exists$OFFSET, exists$LAYOUT.byteSize());
        }

        private static final GroupLayout iterate$LAYOUT =
            (GroupLayout)$LAYOUT.select(groupElement("iterate"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * H5VL_link_iterate_args_t iterate
         * }
         */
        public static final GroupLayout iterate$layout() { return iterate$LAYOUT; }

        private static final long iterate$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * H5VL_link_iterate_args_t iterate
         * }
         */
        public static final long iterate$offset() { return iterate$OFFSET; }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * H5VL_link_iterate_args_t iterate
         * }
         */
        public static MemorySegment iterate(MemorySegment union)
        {
            return union.asSlice(iterate$OFFSET, iterate$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * H5VL_link_iterate_args_t iterate
         * }
         */
        public static void iterate(MemorySegment union, MemorySegment fieldValue)
        {
            MemorySegment.copy(fieldValue, 0L, union, iterate$OFFSET, iterate$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index)
        {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator)
        {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
        {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena,
                                                Consumer<MemorySegment> cleanup)
        {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                                Consumer<MemorySegment> cleanup)
        {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout args$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("args"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hbool_t *exists;
     *     } exists;
     *     H5VL_link_iterate_args_t iterate;
     * } args
     * }
     */
    public static final GroupLayout args$layout() { return args$LAYOUT; }

    private static final long args$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hbool_t *exists;
     *     } exists;
     *     H5VL_link_iterate_args_t iterate;
     * } args
     * }
     */
    public static final long args$offset() { return args$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hbool_t *exists;
     *     } exists;
     *     H5VL_link_iterate_args_t iterate;
     * } args
     * }
     */
    public static MemorySegment args(MemorySegment struct)
    {
        return struct.asSlice(args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hbool_t *exists;
     *     } exists;
     *     H5VL_link_iterate_args_t iterate;
     * } args
     * }
     */
    public static void args(MemorySegment struct, MemorySegment fieldValue)
    {
        MemorySegment.copy(fieldValue, 0L, struct, args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index)
    {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate(layout()); }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
    {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
    {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                            Consumer<MemorySegment> cleanup)
    {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
