// Generated by jextract

package org.hdfgroup.javahdf5;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct H5VL_native_object_get_native_info_t {
 *     unsigned int fields;
 *     H5O_native_info_t *ninfo;
 * }
 * }
 */
public class H5VL_native_object_get_native_info_t {

    H5VL_native_object_get_native_info_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hdf5_h.C_INT.withName("fields"),
        MemoryLayout.paddingLayout(4),
        hdf5_h.C_POINTER.withName("ninfo")
    ).withName("H5VL_native_object_get_native_info_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt fields$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fields"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int fields
     * }
     */
    public static final OfInt fields$layout() {
        return fields$LAYOUT;
    }

    private static final long fields$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int fields
     * }
     */
    public static final long fields$offset() {
        return fields$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int fields
     * }
     */
    public static int fields(MemorySegment struct) {
        return struct.get(fields$LAYOUT, fields$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int fields
     * }
     */
    public static void fields(MemorySegment struct, int fieldValue) {
        struct.set(fields$LAYOUT, fields$OFFSET, fieldValue);
    }

    private static final AddressLayout ninfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ninfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5O_native_info_t *ninfo
     * }
     */
    public static final AddressLayout ninfo$layout() {
        return ninfo$LAYOUT;
    }

    private static final long ninfo$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5O_native_info_t *ninfo
     * }
     */
    public static final long ninfo$offset() {
        return ninfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5O_native_info_t *ninfo
     * }
     */
    public static MemorySegment ninfo(MemorySegment struct) {
        return struct.get(ninfo$LAYOUT, ninfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5O_native_info_t *ninfo
     * }
     */
    public static void ninfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ninfo$LAYOUT, ninfo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

