// Generated by jextract

package org.hdfgroup.javahdf5;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct H5VL_native_file_get_vfd_handle_t {
 *     hid_t fapl_id;
 *     void **file_handle;
 * }
 * }
 */
public class H5VL_native_file_get_vfd_handle_t {

    H5VL_native_file_get_vfd_handle_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hdf5_h.C_LONG.withName("fapl_id"),
        hdf5_h.C_POINTER.withName("file_handle")
    ).withName("H5VL_native_file_get_vfd_handle_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong fapl_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("fapl_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hid_t fapl_id
     * }
     */
    public static final OfLong fapl_id$layout() {
        return fapl_id$LAYOUT;
    }

    private static final long fapl_id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hid_t fapl_id
     * }
     */
    public static final long fapl_id$offset() {
        return fapl_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hid_t fapl_id
     * }
     */
    public static long fapl_id(MemorySegment struct) {
        return struct.get(fapl_id$LAYOUT, fapl_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hid_t fapl_id
     * }
     */
    public static void fapl_id(MemorySegment struct, long fieldValue) {
        struct.set(fapl_id$LAYOUT, fapl_id$OFFSET, fieldValue);
    }

    private static final AddressLayout file_handle$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("file_handle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void **file_handle
     * }
     */
    public static final AddressLayout file_handle$layout() {
        return file_handle$LAYOUT;
    }

    private static final long file_handle$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void **file_handle
     * }
     */
    public static final long file_handle$offset() {
        return file_handle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void **file_handle
     * }
     */
    public static MemorySegment file_handle(MemorySegment struct) {
        return struct.get(file_handle$LAYOUT, file_handle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void **file_handle
     * }
     */
    public static void file_handle(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(file_handle$LAYOUT, file_handle$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

