// Generated by jextract

package org.hdfgroup.javahdf5;

import static java.lang.foreign.MemoryLayout.PathElement.*;
import static java.lang.foreign.ValueLayout.*;

import java.lang.foreign.*;
import java.lang.invoke.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

/**
 * {@snippet lang=c :
 * struct H5VL_native_file_get_info_t {
 *     H5I_type_t type;
 *     H5F_info2_t *finfo;
 * }
 * }
 */
public class H5VL_native_file_get_info_t {

    H5VL_native_file_get_info_t()
    {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT =
        MemoryLayout
            .structLayout(hdf5_h.C_INT.withName("type"), MemoryLayout.paddingLayout(4),
                          hdf5_h.C_POINTER.withName("finfo"))
            .withName("H5VL_native_file_get_info_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() { return $LAYOUT; }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5I_type_t type
     * }
     */
    public static final OfInt type$layout() { return type$LAYOUT; }

    private static final long type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5I_type_t type
     * }
     */
    public static final long type$offset() { return type$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5I_type_t type
     * }
     */
    public static int type(MemorySegment struct) { return struct.get(type$LAYOUT, type$OFFSET); }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5I_type_t type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue)
    {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final AddressLayout finfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("finfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5F_info2_t *finfo
     * }
     */
    public static final AddressLayout finfo$layout() { return finfo$LAYOUT; }

    private static final long finfo$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5F_info2_t *finfo
     * }
     */
    public static final long finfo$offset() { return finfo$OFFSET; }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5F_info2_t *finfo
     * }
     */
    public static MemorySegment finfo(MemorySegment struct) { return struct.get(finfo$LAYOUT, finfo$OFFSET); }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5F_info2_t *finfo
     * }
     */
    public static void finfo(MemorySegment struct, MemorySegment fieldValue)
    {
        struct.set(finfo$LAYOUT, finfo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index)
    {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate(layout()); }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator)
    {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup)
    {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena,
                                            Consumer<MemorySegment> cleanup)
    {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}
