// Generated by jextract

package org.hdfgroup.javahdf5;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct H5VL_datatype_specific_args_t {
 *     H5VL_datatype_specific_t op_type;
 *     union {
 *         struct {
 *             hid_t type_id;
 *         } flush;
 *         struct {
 *             hid_t type_id;
 *         } refresh;
 *     } args;
 * }
 * }
 */
public class H5VL_datatype_specific_args_t {

    H5VL_datatype_specific_args_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hdf5_h.C_INT.withName("op_type"),
        MemoryLayout.paddingLayout(4),
        H5VL_datatype_specific_args_t.args.layout().withName("args")
    ).withName("H5VL_datatype_specific_args_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt op_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("op_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * H5VL_datatype_specific_t op_type
     * }
     */
    public static final OfInt op_type$layout() {
        return op_type$LAYOUT;
    }

    private static final long op_type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * H5VL_datatype_specific_t op_type
     * }
     */
    public static final long op_type$offset() {
        return op_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * H5VL_datatype_specific_t op_type
     * }
     */
    public static int op_type(MemorySegment struct) {
        return struct.get(op_type$LAYOUT, op_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * H5VL_datatype_specific_t op_type
     * }
     */
    public static void op_type(MemorySegment struct, int fieldValue) {
        struct.set(op_type$LAYOUT, op_type$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hid_t type_id;
     *     } flush;
     *     struct {
     *         hid_t type_id;
     *     } refresh;
     * }
     * }
     */
    public static class args {

        args() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            H5VL_datatype_specific_args_t.args.flush.layout().withName("flush"),
            H5VL_datatype_specific_args_t.args.refresh.layout().withName("refresh")
        ).withName("$anon$340:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * }
         * }
         */
        public static class flush {

            flush() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                hdf5_h.C_LONG.withName("type_id")
            ).withName("$anon$342:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfLong type_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("type_id"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static final OfLong type_id$layout() {
                return type_id$LAYOUT;
            }

            private static final long type_id$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static final long type_id$offset() {
                return type_id$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static long type_id(MemorySegment struct) {
                return struct.get(type_id$LAYOUT, type_id$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static void type_id(MemorySegment struct, long fieldValue) {
                struct.set(type_id$LAYOUT, type_id$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout flush$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("flush"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } flush
         * }
         */
        public static final GroupLayout flush$layout() {
            return flush$LAYOUT;
        }

        private static final long flush$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } flush
         * }
         */
        public static final long flush$offset() {
            return flush$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } flush
         * }
         */
        public static MemorySegment flush(MemorySegment union) {
            return union.asSlice(flush$OFFSET, flush$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } flush
         * }
         */
        public static void flush(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, flush$OFFSET, flush$LAYOUT.byteSize());
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * }
         * }
         */
        public static class refresh {

            refresh() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                hdf5_h.C_LONG.withName("type_id")
            ).withName("$anon$347:9");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfLong type_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("type_id"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static final OfLong type_id$layout() {
                return type_id$LAYOUT;
            }

            private static final long type_id$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static final long type_id$offset() {
                return type_id$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static long type_id(MemorySegment struct) {
                return struct.get(type_id$LAYOUT, type_id$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * hid_t type_id
             * }
             */
            public static void type_id(MemorySegment struct, long fieldValue) {
                struct.set(type_id$LAYOUT, type_id$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout refresh$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("refresh"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } refresh
         * }
         */
        public static final GroupLayout refresh$layout() {
            return refresh$LAYOUT;
        }

        private static final long refresh$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } refresh
         * }
         */
        public static final long refresh$offset() {
            return refresh$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } refresh
         * }
         */
        public static MemorySegment refresh(MemorySegment union) {
            return union.asSlice(refresh$OFFSET, refresh$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     hid_t type_id;
         * } refresh
         * }
         */
        public static void refresh(MemorySegment union, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, union, refresh$OFFSET, refresh$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout args$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("args"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hid_t type_id;
     *     } flush;
     *     struct {
     *         hid_t type_id;
     *     } refresh;
     * } args
     * }
     */
    public static final GroupLayout args$layout() {
        return args$LAYOUT;
    }

    private static final long args$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hid_t type_id;
     *     } flush;
     *     struct {
     *         hid_t type_id;
     *     } refresh;
     * } args
     * }
     */
    public static final long args$offset() {
        return args$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hid_t type_id;
     *     } flush;
     *     struct {
     *         hid_t type_id;
     *     } refresh;
     * } args
     * }
     */
    public static MemorySegment args(MemorySegment struct) {
        return struct.asSlice(args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     struct {
     *         hid_t type_id;
     *     } flush;
     *     struct {
     *         hid_t type_id;
     *     } refresh;
     * } args
     * }
     */
    public static void args(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, args$OFFSET, args$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

