// Generated by jextract

package org.hdfgroup.javahdf5;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct H5VL_loc_by_idx {
 *     const char *name;
 *     H5_index_t idx_type;
 *     H5_iter_order_t order;
 *     hsize_t n;
 *     hid_t lapl_id;
 * } H5VL_loc_by_idx_t
 * }
 */
public class H5VL_loc_by_idx_t extends H5VL_loc_by_idx {

    H5VL_loc_by_idx_t() {
        // Should not be called directly
    }
}

