Granular BitRound filter is available for quantization and decoding.
....Create dataset ................
....Writing Granular BitRound-quantized data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property
   Filter identifier is 32023
   Number of parameters is 5 with the values 3, 4, 0, 0, 0
   To find more about the filter check Granular BitRound filter
....Reading Granular BitRound-quantized data ................
Maximum value in DS1 is 1.84467e+19
Granular BitRound filter is available now since H5Dread triggered loading of the filter.
