FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential cmake cmake-curses-gui doxygen git graphviz \
  less libtool-bin libyajl-dev mpi-default-dev valgrind wget