FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential cmake cmake-curses-gui default-jdk doxygen gfortran git graphviz \
  less libtool-bin libyajl-dev mpi-default-dev ninja-build pkg-config valgrind wget
