#!/bin/sh
# Site configuration -- do not distribute this file.

CC="cc -ansi -64"

# -woff 1174	about function declared but not used
# -woff 1429	about long long type non-standard
# -woff 1209    about constant expressions
# -woff 1196    about __vfork() being implicitly declared, config prob.
warn="-fullwarn -woff 1174,1429,1209,1196"
#warn="-woff 1174,1429,1209,1196"

profile="-pg"

debug="-g -DH5AC_DEBUG -DH5B_DEBUG -DH5F_DEBUG -DH5G_DEBUG -UH5O_DEBUG -DH5T_DEBUG -DH5F_OPT_SEEK=0"

#production="-O -DNDEBUG"

default_mode='$debug $warn -DH5F_LOW_DFLT=H5F_LOW_SEC2'

RANLIB=:		# SGI needs not ranlib

# Don't set CFLAGS if the user already did.
if test -z "$CFLAGS"; then
   CFLAGS="`eval echo ${HDF5_MODE:-$default_mode}`"
   export CFLAGS
fi
