HDF5 C++ API: H5::Attribute Class Reference
H5::Attribute Class Reference
Class Attribute operates on HDF5 attributes.
#include <H5Attribute.h>
Public Member Functions
virtual void close ()
Closes this attribute.
H5std_string getFileName () const
Gets the name of the file, in which this attribute belongs.
ssize_t getName (char *attr_name, size_t buf_size=0) const
Gets the name of this attribute, returning its length.
H5std_string getName (size_t len) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an integer specifying a desired length to be retrieved of the name.
H5std_string getName () const
Returns the name of this attribute as an H5std_string.
ssize_t getName (H5std_string &attr_name, size_t len=0) const
Gets the name of this attribute, returning its length.
ssize_t getName (size_t buf_size, H5std_string &attr_name) const
This function is replaced by the previous function, which provides more convenient prototype. It will be removed in future release.
virtual DataSpace getSpace () const
Gets a copy of the dataspace for this attribute.
virtual hsize_t getStorageSize () const
Returns the amount of storage size required for this attribute.
virtual size_t getInMemDataSize () const
Gets the size in memory of the attribute's data.
void read (const DataType &mem_type, void *buf) const
Reads data from this attribute.
void read (const DataType &mem_type, H5std_string &strg) const
This is an overloaded member function, provided for convenience. It reads a H5std_string from this attribute.
void write (const DataType &mem_type, const void *buf) const
Writes data to this attribute.
void write (const DataType &mem_type, const H5std_string &strg) const
This is an overloaded member function, provided for convenience. It writes a H5std_string to this attribute.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a file specified by this attribute, to disk.
virtual H5std_string fromClass () const
Returns this class name.
Attribute (const hid_t attr_id)
Creates an Attribute object using the id of an existing attribute.
Attribute (const Attribute &original)
Copy constructor: makes a copy of the original Attribute object.
Attribute ()
Default constructor: Creates a stub attribute.
virtual hid_t getId () const
Get the id of this attribute.
virtual ~Attribute ()
Properly terminates access to this attribute.
Public Member Functions inherited from H5::AbstractDs
DataType getDataType () const
Returns the generic datatype of this abstract dataset, which can be a dataset or an attribute.
ArrayType getArrayType () const
Returns the array datatype of this abstract dataset which can be a dataset or an attribute.
CompType getCompType () const
Returns the compound datatype of this abstract dataset which can be a dataset or an attribute.
EnumType getEnumType () const
Returns the enumeration datatype of this abstract dataset which can be a dataset or an attribute.
IntType getIntType () const
Returns the integer datatype of this abstract dataset which can be a dataset or an attribute.
FloatType getFloatType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
StrType getStrType () const
Returns the string datatype of this abstract dataset which can be a dataset or an attribute.
VarLenType getVarLenType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
H5T_class_t getTypeClass () const
Returns the class of the datatype that is used by this object, which can be a dataset or an attribute.
AbstractDs (const AbstractDs &original)
Copy constructor: makes a copy of the original AbstractDs object.
virtual ~AbstractDs ()
Noop destructor.
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
IdComponent (const hid_t h5_id)
Creates an IdComponent object using the id of an existing object.
IdComponent (const IdComponent &original)
Copy constructor: makes a copy of the original IdComponent object.
virtual ~IdComponent ()
Noop destructor.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
Protected Member Functions inherited from H5::AbstractDs
AbstractDs ()
Default constructor.
AbstractDs (const hid_t ds_id)
Creates an AbstractDs instance using an existing id.
Protected Member Functions inherited from H5::IdComponent
IdComponent ()
Detailed Description
An attribute has many characteristics similar to a dataset, thus both Attribute and DataSet are derivatives of AbstractDs. Attribute also inherits from IdComponent because an attribute is an HDF5 component that is identified by an identifier.
Constructor & Destructor Documentation
H5::Attribute::Attribute (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing attribute
Exceptions
H5::AttributeIException
H5::Attribute::Attribute (const Attribute & original)
Parameters
original - IN: Original Attribute object to copy
References getId(), and H5::IdComponent::incRefCount().
H5::Attribute::Attribute ()
H5::Attribute::~Attribute () virtual
References close(), and H5::Exception::getDetailMsg().
Member Function Documentation
void H5::Attribute::close () virtual
Exceptions
H5::AttributeIException
Referenced by ~Attribute().
void H5::Attribute::flush (H5F_scope_t scope) const
Parameters
scope - IN: Specifies the scope of the flushing action, which can be either of these values:
H5F_SCOPE_GLOBAL - Flushes the entire virtual file
H5F_SCOPE_LOCAL - Flushes only the specified file
Exceptions
H5::AttributeIException
Description
This attribute is used to identify the file to be flushed.
References getId().
virtual H5std_string H5::Attribute::fromClass () const inline virtual
Implements H5::AbstractDs.
H5std_string H5::Attribute::getFileName () const
Returns
File name
Exceptions
H5::IdComponentException
References H5::Exception::getDetailMsg().
hid_t H5::Attribute::getId () const virtual
Returns
Attribute identifier
Referenced by Attribute(), H5::DataSet::DataSet(), H5::DataType::DataType(), H5::H5Location::dereference(), flush(), and H5::Group::Group().
size_t H5::Attribute::getInMemDataSize () const virtual
Returns
Size of data (in memory)
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
ssize_t H5::Attribute::getName (char * attr_name, size_t buf_size = 0) const
Parameters
attr_name - OUT: Buffer for the name string as char*
buf_size - IN: Length of the buffer, default to 0
Returns
Actual length of the attribute name
Exceptions
H5::AttributeIException
Description
This function retrieves buf_size chars of the attribute's name including null termination. Thus, if the actual length of the name is more than buf_size-1, the retrieved name will be truncated to accommodate the null terminator. To get length of the attribute's name for buffer allocation, an application can call this function passing in NULL for the first argument and ignore the second argument.
H5std_string H5::Attribute::getName (size_t len) const
Returns
Name (or part of name) of the attribute
Parameters
len - IN: Desired length of the name
Exceptions
H5::AttributeIException
References getName().
H5std_string H5::Attribute::getName () const
Returns
Name of the attribute
Exceptions
H5::AttributeIException
Referenced by getName().
ssize_t H5::Attribute::getName (H5std_string & attr_name, size_t len = 0) const
Parameters
attr_name - OUT: Buffer for the name string as H5std_string
len - IN: Desired length of the name, default to 0
Returns
Actual length of the attribute name
Exceptions
H5::AttributeIException
Description
This function retrieves the attribute's name as a string. The buf_size can specify a specific length or default to 0, in which case the entire name will be retrieved.
References getName().
ssize_t H5::Attribute::getName (size_t len, H5std_string & attr_name) const
Parameters
len - IN: Desired length of the name
attr_name - OUT: Buffer for the name string
Returns
Actual length of the attribute name
Exceptions
H5::AttributeIException
References getName().
DataSpace H5::Attribute::getSpace () const virtual
Returns
Dataspace instance
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
hsize_t H5::Attribute::getStorageSize () const virtual
Returns
Size of the storage or 0, for no data
Exceptions
H5::AttributeIException
Implements H5::AbstractDs.
void H5::Attribute::read (const DataType & mem_type, void * buf) const
Parameters
mem_type - IN: Attribute datatype (in memory)
buf - OUT: Buffer for read data
Exceptions
H5::AttributeIException
References H5::DataType::getId().
void H5::Attribute::read (const DataType & mem_type, H5std_string & strg) const
Parameters
mem_type - IN: Attribute datatype (in memory)
strg - IN: Buffer for read string
Exceptions
H5::AttributeIException
References H5::DataType::getId().
void H5::Attribute::write (const DataType & mem_type, const void * buf) const
Parameters
mem_type - IN: Attribute datatype (in memory)
buf - IN: Data to be written
Exceptions
H5::AttributeIException
References H5::DataType::getId().
void H5::Attribute::write (const DataType & mem_type, const H5std_string & strg) const
Parameters
mem_type - IN: Attribute datatype (in memory)
strg - IN: Data to be written
Exceptions
H5::AttributeIException
References H5::DataType::getId().
The documentation for this class was generated from the following files:
H5Attribute.h
H5Attribute.cpp