HDF5 C++ API: H5::Group Class Reference
H5::Group Class Reference
Class Group represents an HDF5 group.
#include <H5Group.h>
Public Member Functions
virtual void close ()
Closes this group.
virtual H5std_string fromClass () const
Returns this class name.
virtual void throwException (const H5std_string &func_name, const H5std_string &msg) const
Throws H5::GroupIException.
virtual hid_t getLocId () const
Returns the id of this group.
Group (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 group, creates a Group object.
Group (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 group, creates a Group object.
Group ()
Default constructor: creates a stub Group.
Group (const Group &original)
Copy constructor: makes a copy of the original Group object.
virtual hid_t getId () const
Get the id of this group.
virtual ~Group ()
Properly terminates access to this group.
Group (const hid_t group_id)
Creates a Group object using the id of an existing group.
Public Member Functions inherited from H5::H5Location
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Creates an attribute for a group, dataset, or named datatype.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const char *name) const
Opens an attribute given its name.
Attribute openAttribute (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const unsigned int idx) const
Opens an attribute given its index.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which this HDF5 object belongs.
int getNumAttrs () const
Returns the number of attributes attached to this HDF5 object.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
bool attrExists (const char *name) const
Checks whether the named attribute exists at this location.
bool attrExists (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void renameAttr (const char *oldname, const char *newname) const
Renames the named attribute from this object.
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for the names.
void removeAttr (const char *name) const
Removes the named attribute from this object.
void removeAttr (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
void dereference (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an attribute.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
IdComponent (const hid_t h5_id)
Creates an IdComponent object using the id of an existing object.
IdComponent (const IdComponent &original)
Copy constructor: makes a copy of the original IdComponent object.
virtual ~IdComponent ()
Noop destructor.
Public Member Functions inherited from H5::CommonFG
Group createGroup (const char *name, size_t size_hint=0) const
Creates a new group at this location which can be a file or another group.
Group createGroup (const H5std_string &name, size_t size_hint=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Group openGroup (const char *name) const
Opens an existing group in a location which can be a file or another group.
Group openGroup (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet createDataSet (const char *name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT) const
Creates a new dataset at this location.
DataSet createDataSet (const H5std_string &name, const DataType &data_type, const DataSpace &data_space, const DSetCreatPropList &create_plist=DSetCreatPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
DataSet openDataSet (const char *name) const
Opens an existing dataset at this location.
DataSet openDataSet (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5std_string getLinkval (const char *link_name, size_t size=0) const
Returns the name of the object that the symbolic link points to.
H5std_string getLinkval (const H5std_string &link_name, size_t size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
hsize_t getNumObjs () const
Returns the number of objects in this group.
H5std_string getObjnameByIdx (hsize_t idx) const
Returns the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, char *name, size_t size) const
Retrieves the name of an object in this group, given the object's index.
ssize_t getObjnameByIdx (hsize_t idx, H5std_string &name, size_t size) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
H5O_type_t childObjType (const H5std_string &objname) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for the object's name.
H5O_type_t childObjType (const char *objname) const
Returns the type of an object in this file/group, given the object's name.
H5O_type_t childObjType (hsize_t index, H5_index_t index_type=H5_INDEX_NAME, H5_iter_order_t order=H5_ITER_INC, const char *objname=".") const
Returns the type of an object in this file/group, given the object's index and its type and order.
H5G_obj_t getObjTypeByIdx (hsize_t idx) const
H5G_obj_t getObjTypeByIdx (hsize_t idx, char *type_name) const
H5G_obj_t getObjTypeByIdx (hsize_t idx, H5std_string &type_name) const
void getObjinfo (const char *name, hbool_t follow_link, H5G_stat_t &statbuf) const
Returns information about an object.
void getObjinfo (const H5std_string &name, hbool_t follow_link, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void getObjinfo (const char *name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above functions in that it doesn't have the paramemter follow_link.
void getObjinfo (const H5std_string &name, H5G_stat_t &statbuf) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
int iterateElems (const char *name, int *idx, H5G_iterate_t op, void *op_data)
Iterates a user's function over the entries of a group.
int iterateElems (const H5std_string &name, int *idx, H5G_iterate_t op, void *op_data)
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void link (H5L_type_t link_type, const char *curr_name, const char *new_name) const
Creates a link of the specified type from new_name to curr_name.
void link (H5L_type_t link_type, const H5std_string &curr_name, const H5std_string &new_name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for curr_name and new_name.
void unlink (const char *name) const
Removes the specified name at this location.
void unlink (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void mount (const char *name, const H5File &child, const PropList &plist) const
Mounts the file child onto this group.
void mount (const char *name, H5File &child, PropList &plist) const
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
void mount (const H5std_string &name, const H5File &child, const PropList &plist) const
This is an overloaded member function, provided for convenience. It takes an H5std_string for name.
void mount (const H5std_string &name, H5File &child, PropList &plist) const
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
void unmount (const char *name) const
Unmounts the specified file.
void unmount (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void move (const char *src, const char *dst) const
Renames an object at this location.
void move (const H5std_string &src, const H5std_string &dst) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for src and dst.
DataType openDataType (const char *name) const
Opens the named generic datatype at this location.
DataType openDataType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
ArrayType openArrayType (const char *name) const
Opens the named array datatype at this location.
ArrayType openArrayType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
CompType openCompType (const char *name) const
Opens the named compound datatype at this location.
CompType openCompType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
EnumType openEnumType (const char *name) const
Opens the named enumeration datatype at this location.
EnumType openEnumType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
IntType openIntType (const char *name) const
Opens the named integer datatype at this location.
IntType openIntType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
FloatType openFloatType (const char *name) const
Opens the named floating-point datatype at this location.
FloatType openFloatType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
StrType openStrType (const char *name) const
Opens the named string datatype at this location.
StrType openStrType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
VarLenType openVarLenType (const char *name) const
Opens the named variable length datatype at this location.
VarLenType openVarLenType (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
Protected Member Functions inherited from H5::H5Location
H5Location ()
H5Location (const hid_t loc_id)
H5Location (const H5Location &original)
virtual ~H5Location ()
Protected Member Functions inherited from H5::IdComponent
IdComponent ()
Detailed Description
It inherits many operations from H5Location and CommonFG.
Examples:
h5group.cpp.
Constructor & Destructor Documentation
H5::Group::Group (const H5Location & loc, const void * ref, H5R_type_t ref_type = H5R_OBJECT, const PropList & plist = PropList::DEFAULT)
Parameters
loc - IN: Specifying location referenced object is in
ref - IN: Reference pointer
ref_type - IN: Reference type - default to H5R_OBJECT
plist - IN: Property list - default to PropList::DEFAULT
Exceptions
H5::ReferenceException
Description
obj can be DataSet, Group, or named DataType, that is a datatype that has been named by DataType::commit.
References H5::H5Location::getId().
H5::Group::Group (const Attribute & attr, const void * ref, H5R_type_t ref_type = H5R_OBJECT, const PropList & plist = PropList::DEFAULT)
Parameters
attr - IN: Specifying location where the referenced object is in
ref - IN: Reference pointer
ref_type - IN: Reference type - default to H5R_OBJECT
plist - IN: Property list - default to PropList::DEFAULT
Exceptions
H5::ReferenceException
References H5::Attribute::getId().
H5::Group::Group ()
H5::Group::Group (const Group & original)
Parameters
original - IN: Original group to copy
References getId(), and H5::IdComponent::incRefCount().
H5::Group::~Group () virtual
References close(), and H5::Exception::getDetailMsg().
H5::Group::Group (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing group
Member Function Documentation
void H5::Group::close () virtual
Exceptions
H5::GroupIException
Referenced by ~Group().
virtual H5std_string H5::Group::fromClass () const inline virtual
hid_t H5::Group::getId () const virtual
Returns
Group identifier
Implements H5::H5Location.
Referenced by getLocId(), and Group().
hid_t H5::Group::getLocId () const virtual
Returns
Id of this group
References getId().
void H5::Group::throwException (const H5std_string & func_name, const H5std_string & msg) const virtual
Parameters
func_name - Name of the function where failure occurs
msg - Message describing the failure
Exceptions
H5::GroupIException
The documentation for this class was generated from the following files:
H5Group.h
H5Group.cpp