HDF5 C++ API: H5::CompType Class Reference
H5::CompType Class Reference
CompType is a derivative of a DataType and operates on HDF5 compound datatypes.
#include <H5CompType.h>
Public Member Functions
CompType ()
Default constructor: Creates a stub compound datatype.
CompType (const hid_t existing_id)
Creates a CompType object using the id of an existing datatype.
CompType (size_t size)
Creates an empty compound datatype given a size, in bytes.
CompType (const DataSet &dataset)
Gets the compound datatype of the specified dataset.
CompType (const CompType &original)
Copy constructor: makes copy of the original CompType object.
H5T_class_t getMemberClass (unsigned member_num) const
Gets the type class of the specified member.
int getMemberIndex (const char *name) const
Returns the index of a member in this compound datatype.
int getMemberIndex (const H5std_string &name) const
size_t getMemberOffset (unsigned memb_no) const
Returns the byte offset of the beginning of a member with respect to the beginning of the compound data type datum.
H5std_string getMemberName (unsigned member_num) const
Returns the name of a member in this compound datatype.
DataType getMemberDataType (unsigned member_num) const
Returns the generic datatype of the specified member in this compound datatype.
ArrayType getMemberArrayType (unsigned member_num) const
Returns the array datatype of the specified member in this compound datatype.
CompType getMemberCompType (unsigned member_num) const
Returns the compound datatype of the specified member in this compound datatype.
EnumType getMemberEnumType (unsigned member_num) const
Returns the enumeration datatype of the specified member in this compound datatype.
IntType getMemberIntType (unsigned member_num) const
Returns the integer datatype of the specified member in this compound datatype.
FloatType getMemberFloatType (unsigned member_num) const
Returns the floating-point datatype of the specified member in this compound datatype.
StrType getMemberStrType (unsigned member_num) const
Returns the string datatype of the specified member in this compound datatype.
VarLenType getMemberVarLenType (unsigned member_num) const
Returns the variable length datatype of the specified member in this compound datatype.
int getNmembers () const
Returns the number of members in this compound datatype.
void insertMember (const H5std_string &name, size_t offset, const DataType &new_member) const
Inserts a new member to this compound datatype.
void pack () const
Recursively removes padding from within a compound datatype.
void setSize (size_t size) const
Sets the total size for this compound datatype.
virtual H5std_string fromClass () const
Returns this class name.
virtual ~CompType ()
Properly terminates access to this compound datatype.
Public Member Functions inherited from H5::DataType
DataType (const H5T_class_t type_class, size_t size)
Creates a object given its class and size.
DataType (const DataType &original)
Copy constructor: makes a copy of the original DataType object.
DataType (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 group, creates a DataType object.
DataType (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 group, creates a DataType object.
virtual void close ()
Closes the datatype if it is not a predefined type.
void copy (const DataType &like_type)
Copies an existing datatype to this datatype object.
void copy (const DataSet &dset)
Copies the datatype of the given dataset to this datatype object.
H5T_class_t getClass () const
Returns the datatype class identifier.
void commit (const H5Location &loc, const char *name)
Commits a transient datatype to a file, creating a new named datatype.
void commit (const H5Location &loc, const H5std_string &name)
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void commit (H5Location &loc, const char *name)
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
void commit (H5Location &loc, const H5std_string &name)
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
bool committed () const
Determines whether a datatype is a named type or a transient type.
H5T_conv_t find (const DataType &dest, H5T_cdata_t **pcdata) const
Finds a conversion function that can handle a conversion from this datatype to the specified datatype, dest.
void convert (const DataType &dest, size_t nelmts, void *buf, void *background, const PropList &plist=PropList::DEFAULT) const
Converts data from this datatype to the specified datatypes.
DataType & operator= (const DataType &rhs)
Assignment operator.
bool operator== (const DataType &compared_type) const
Compares this DataType against the given one to determines whether the two objects refer to the same actual datatype.
void lock () const
Locks a datatype, making it read-only and non-destructible.
size_t getSize () const
Returns the size of a datatype.
DataType getSuper () const
Returns the base datatype from which a datatype is derived.
void registerFunc (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Registers the specified conversion function.
void registerFunc (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void unregister (H5T_pers_t pers, const char *name, const DataType &dest, H5T_conv_t func) const
Removes a conversion function from all conversion paths.
void unregister (H5T_pers_t pers, const H5std_string &name, const DataType &dest, H5T_conv_t func) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
void setTag (const char *tag) const
Tags an opaque datatype.
void setTag (const H5std_string &tag) const
This is an overloaded member function, provided for convenience. It differs from the above function only in the type of the argument name.
H5std_string getTag () const
Gets the tag associated with an opaque datatype.
bool detectClass (H5T_class_t cls) const
Checks whether a datatype contains (or is) a certain type of datatype.
bool isVariableStr () const
Check whether this datatype is a variable-length string.
DataType (const hid_t type_id)
Creates a datatype using an existing datatype's id.
DataType ()
Default constructor: Creates a stub datatype.
virtual hid_t getId () const
Get the id of this datatype.
virtual ~DataType ()
Properly terminates access to this datatype.
Public Member Functions inherited from H5::H5Location
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Creates an attribute for a group, dataset, or named datatype.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const char *name) const
Opens an attribute given its name.
Attribute openAttribute (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const unsigned int idx) const
Opens an attribute given its index.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which this HDF5 object belongs.
int getNumAttrs () const
Returns the number of attributes attached to this HDF5 object.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
bool attrExists (const char *name) const
Checks whether the named attribute exists at this location.
bool attrExists (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void renameAttr (const char *oldname, const char *newname) const
Renames the named attribute from this object.
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for the names.
void removeAttr (const char *name) const
Removes the named attribute from this object.
void removeAttr (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
void dereference (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an attribute.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
IdComponent (const hid_t h5_id)
Creates an IdComponent object using the id of an existing object.
IdComponent (const IdComponent &original)
Copy constructor: makes a copy of the original IdComponent object.
virtual ~IdComponent ()
Noop destructor.
Additional Inherited Members
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
Protected Member Functions inherited from H5::H5Location
H5Location ()
H5Location (const hid_t loc_id)
H5Location (const H5Location &original)
virtual ~H5Location ()
Protected Member Functions inherited from H5::IdComponent
IdComponent ()
Detailed Description
Examples:
compound.cpp.
Constructor & Destructor Documentation
H5::CompType::CompType ()
H5::CompType::CompType (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing compound datatype
H5::CompType::CompType (size_t size)
Parameters
size - IN: Number of bytes in the datatype to create
Exceptions
H5::DataTypeIException
H5::CompType::CompType (const DataSet & dataset)
Parameters
dataset - IN: Dataset that this enum datatype associates with
Returns
CompType instance
Exceptions
H5::DataTypeIException
References H5::DataSet::getId().
H5::CompType::CompType (const CompType & original)
Parameters
original - IN: Original CompType instance
H5::CompType::~CompType () virtual
Member Function Documentation
virtual H5std_string H5::CompType::fromClass () const inline virtual
Reimplemented from H5::DataType.
ArrayType H5::CompType::getMemberArrayType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
ArrayType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
H5T_class_t H5::CompType::getMemberClass (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
Type class of the member
Exceptions
H5::DataTypeIException
CompType H5::CompType::getMemberCompType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
CompType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
DataType H5::CompType::getMemberDataType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
DataType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
EnumType H5::CompType::getMemberEnumType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
EnumType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
FloatType H5::CompType::getMemberFloatType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
FloatType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
int H5::CompType::getMemberIndex (const char * name) const
Parameters
name - IN: Name of the member
Returns
Index of member
Exceptions
H5::DataTypeIException
Description
Members are stored in no particular order with numbers 0 through N-1, where N is the value returned by the member function CompType::getNmembers.
Referenced by getMemberIndex().
int H5::CompType::getMemberIndex (const H5std_string & name) const
References getMemberIndex().
IntType H5::CompType::getMemberIntType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
IntType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
H5std_string H5::CompType::getMemberName (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
Name of member
Exceptions
H5::DataTypeIException
size_t H5::CompType::getMemberOffset (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
Byte offset
Exceptions
H5::DataTypeIException Members are stored in no particular order with numbers 0 through N-1, where N is the value returned by the member function CompType::getNmembers.
StrType H5::CompType::getMemberStrType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
StrType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
VarLenType H5::CompType::getMemberVarLenType (unsigned member_num) const
Parameters
member_num - IN: Zero-based index of the member
Returns
VarLenType instance
Exceptions
H5::DataTypeIException
References H5::Exception::getDetailMsg().
int H5::CompType::getNmembers () const
Returns
Number of members
Exceptions
H5::DataTypeIException
void H5::CompType::insertMember (const H5std_string & name, size_t offset, const DataType & new_member) const
Parameters
name - IN: Name of the new member
offset - IN: Offset in memory structure of the field to insert
new_member - IN: New member to be inserted
Exceptions
H5::DataTypeIException
References H5::DataType::getId().
void H5::CompType::pack () const
Exceptions
H5::DataTypeIException
void H5::CompType::setSize (size_t size) const
Parameters
size - IN: Size to set
Exceptions
H5::DataTypeIException
The documentation for this class was generated from the following files:
H5CompType.h
H5CompType.cpp