HDF5 C++ API: H5::DataSet Class Reference
H5::DataSet Class Reference
Class DataSet operates on HDF5 datasets.
#include <H5DataSet.h>
Public Member Functions
virtual void close ()
Closes this dataset.
void extend (const hsize_t *size) const
Extends a dataset with unlimited dimension.
void fillMemBuf (const void *fill, const DataType &fill_type, void *buf, const DataType &buf_type, const DataSpace &space) const
Fills a selection in memory with a value.
void fillMemBuf (const void *fill, DataType &fill_type, void *buf, DataType &buf_type, DataSpace &space)
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
void fillMemBuf (void *buf, const DataType &buf_type, const DataSpace &space) const
Fills a selection in memory with 0.
void fillMemBuf (void *buf, DataType &buf_type, DataSpace &space)
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
DSetCreatPropList getCreatePlist () const
Gets the dataset creation property list.
haddr_t getOffset () const
Returns the address of this dataset in the file.
virtual DataSpace getSpace () const
Gets a copy of the dataspace of this dataset.
void getSpaceStatus (H5D_space_status_t &status) const
Determines whether space has been allocated for a dataset.
virtual hsize_t getStorageSize () const
Returns the amount of storage required for a dataset.
virtual size_t getInMemDataSize () const
Gets the size in memory of the dataset's data.
hsize_t getVlenBufSize (const DataType &type, const DataSpace &space) const
Returns the number of bytes required to store VL data.
hsize_t getVlenBufSize (DataType &type, DataSpace &space) const
This is an overloaded member function, kept for backward compatibility. It differs from the above function in that it misses const's. This wrapper will be removed in future release.
void read (void *buf, const DataType &mem_type, const DataSpace &mem_space=DataSpace::ALL, const DataSpace &file_space=DataSpace::ALL, const DSetMemXferPropList &xfer_plist=DSetMemXferPropList::DEFAULT) const
Reads raw data from the specified dataset.
void read (H5std_string &buf, const DataType &mem_type, const DataSpace &mem_space=DataSpace::ALL, const DataSpace &file_space=DataSpace::ALL, const DSetMemXferPropList &xfer_plist=DSetMemXferPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It takes a reference to a H5std_string for the buffer.
void write (const void *buf, const DataType &mem_type, const DataSpace &mem_space=DataSpace::ALL, const DataSpace &file_space=DataSpace::ALL, const DSetMemXferPropList &xfer_plist=DSetMemXferPropList::DEFAULT) const
Writes raw data from an application buffer to a dataset.
void write (const H5std_string &buf, const DataType &mem_type, const DataSpace &mem_space=DataSpace::ALL, const DataSpace &file_space=DataSpace::ALL, const DSetMemXferPropList &xfer_plist=DSetMemXferPropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It takes a reference to a H5std_string for the buffer.
int iterateElems (void *buf, const DataType &type, const DataSpace &space, H5D_operator_t op, void *op_data=NULL)
Iterates over all selected elements in a dataspace.
virtual H5std_string fromClass () const
Returns this class name.
DataSet (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 location, creates a DataSet object.
DataSet (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Given a reference, ref, to an hdf5 attribute, creates a DataSet object.
DataSet ()
Default constructor: creates a stub DataSet.
DataSet (const DataSet &original)
Copy constructor: makes a copy of the original DataSet object.
DataSet (const hid_t existing_id)
Creates an DataSet object using the id of an existing dataset.
virtual hid_t getId () const
Get the id of this dataset.
virtual ~DataSet ()
Properly terminates access to this dataset.
Public Member Functions inherited from H5::H5Location
Attribute createAttribute (const char *name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
Creates an attribute for a group, dataset, or named datatype.
Attribute createAttribute (const H5std_string &name, const DataType &type, const DataSpace &space, const PropList &create_plist=PropList::DEFAULT) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const char *name) const
Opens an attribute given its name.
Attribute openAttribute (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
Attribute openAttribute (const unsigned int idx) const
Opens an attribute given its index.
void flush (H5F_scope_t scope) const
Flushes all buffers associated with a location to disk.
H5std_string getFileName () const
Gets the name of the file, in which this HDF5 object belongs.
int getNumAttrs () const
Returns the number of attributes attached to this HDF5 object.
H5G_obj_t getObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
H5O_type_t getRefObjType (void *ref, H5R_type_t ref_type=H5R_OBJECT) const
Retrieves the type of object that an object reference points to.
int iterateAttrs (attr_operator_t user_op, unsigned *idx=NULL, void *op_data=NULL)
Iterates a user's function over all the attributes of an H5 object, which may be a group, dataset or named datatype.
bool attrExists (const char *name) const
Checks whether the named attribute exists at this location.
bool attrExists (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void renameAttr (const char *oldname, const char *newname) const
Renames the named attribute from this object.
void renameAttr (const H5std_string &oldname, const H5std_string &newname) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for the names.
void removeAttr (const char *name) const
Removes the named attribute from this object.
void removeAttr (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes a reference to an H5std_string for name.
void setComment (const char *name, const char *comment) const
Sets or resets the comment for an object specified by its name.
void setComment (const H5std_string &name, const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name and comment.
void setComment (const char *comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it doesn't take an object name.
void setComment (const H5std_string &comment) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for comment.
ssize_t getComment (const char *name, size_t buf_size, char *comment) const
Retrieves the comment for this location, returning its length.
H5std_string getComment (const char *name, size_t buf_size=0) const
Returns the comment as string for this location, returning its length.
H5std_string getComment (const H5std_string &name, size_t buf_size=0) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void removeComment (const char *name) const
Removes the comment from an object specified by its name.
void removeComment (const H5std_string &name) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void reference (void *ref, const char *name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it does not take a DataSpace object and the reference type must be specified.
void reference (void *ref, const H5std_string &name, H5R_type_t ref_type=H5R_OBJECT) const
This is an overloaded function, provided for your convenience. It differs from the above function in that it takes an H5std_string for the object's name.
void reference (void *ref, const char *name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
Creates a reference to an HDF5 object or a dataset region.
void reference (void *ref, const H5std_string &name, const DataSpace &dataspace, H5R_type_t ref_type=H5R_DATASET_REGION) const
This is an overloaded member function, provided for convenience. It differs from the above function in that it takes an H5std_string for name.
void dereference (const H5Location &loc, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an HDF5 object.
void dereference (const Attribute &attr, const void *ref, H5R_type_t ref_type=H5R_OBJECT, const PropList &plist=PropList::DEFAULT)
Dereferences a reference into an HDF5 object, given an attribute.
DataSpace getRegion (void *ref, H5R_type_t ref_type=H5R_DATASET_REGION) const
Public Member Functions inherited from H5::IdComponent
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
IdComponent (const hid_t h5_id)
Creates an IdComponent object using the id of an existing object.
IdComponent (const IdComponent &original)
Copy constructor: makes a copy of the original IdComponent object.
virtual ~IdComponent ()
Noop destructor.
Public Member Functions inherited from H5::AbstractDs
DataType getDataType () const
Returns the generic datatype of this abstract dataset, which can be a dataset or an attribute.
ArrayType getArrayType () const
Returns the array datatype of this abstract dataset which can be a dataset or an attribute.
CompType getCompType () const
Returns the compound datatype of this abstract dataset which can be a dataset or an attribute.
EnumType getEnumType () const
Returns the enumeration datatype of this abstract dataset which can be a dataset or an attribute.
IntType getIntType () const
Returns the integer datatype of this abstract dataset which can be a dataset or an attribute.
FloatType getFloatType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
StrType getStrType () const
Returns the string datatype of this abstract dataset which can be a dataset or an attribute.
VarLenType getVarLenType () const
Returns the floating-point datatype of this abstract dataset, which can be a dataset or an attribute.
H5T_class_t getTypeClass () const
Returns the class of the datatype that is used by this object, which can be a dataset or an attribute.
AbstractDs (const AbstractDs &original)
Copy constructor: makes a copy of the original AbstractDs object.
virtual ~AbstractDs ()
Noop destructor.
Static Public Member Functions
static void vlenReclaim (const DataType &type, const DataSpace &space, const DSetMemXferPropList &xfer_plist, void *buf)
Reclaims VL datatype memory buffers.
static void vlenReclaim (void *buf, const DataType &type, const DataSpace &space=DataSpace::ALL, const DSetMemXferPropList &xfer_plist=DSetMemXferPropList::DEFAULT)
Reclaims VL datatype memory buffers.
Static Public Member Functions inherited from H5::IdComponent
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
Additional Inherited Members
Protected Member Functions inherited from H5::H5Location
H5Location ()
H5Location (const hid_t loc_id)
H5Location (const H5Location &original)
virtual ~H5Location ()
Protected Member Functions inherited from H5::IdComponent
IdComponent ()
Protected Member Functions inherited from H5::AbstractDs
AbstractDs ()
Default constructor.
AbstractDs (const hid_t ds_id)
Creates an AbstractDs instance using an existing id.
Detailed Description
An datasets has many characteristics similar to an attribute, thus both Attribute and DataSet are derivatives of AbstractDs. DataSet also inherits from H5Object because a dataset is an HDF5 object.
Examples:
chunks.cpp, compound.cpp, create.cpp, extend_ds.cpp, h5group.cpp, readdata.cpp, and writedata.cpp.
Constructor & Destructor Documentation
H5::DataSet::DataSet (const H5Location & loc, const void * ref, H5R_type_t ref_type = H5R_OBJECT, const PropList & plist = PropList::DEFAULT)
Parameters
loc - IN: Dataset reference object is in or location of object that the dataset is located within.
ref - IN: Reference pointer
ref_type - IN: Reference type - default to H5R_OBJECT
plist - IN: Property list - default to PropList::DEFAULT
Exceptions
H5::DataSetIException
Description
loc can be DataSet, Group, H5File, or named DataType, that is a datatype that has been named by DataType::commit.
References H5::H5Location::getId().
H5::DataSet::DataSet (const Attribute & attr, const void * ref, H5R_type_t ref_type = H5R_OBJECT, const PropList & plist = PropList::DEFAULT)
Parameters
attr - IN: Specifying location where the referenced object is in
ref - IN: Reference pointer
ref_type - IN: Reference type - default to H5R_OBJECT
plist - IN: Property list - default to PropList::DEFAULT
Exceptions
H5::ReferenceException
References H5::Attribute::getId().
H5::DataSet::DataSet ()
H5::DataSet::DataSet (const DataSet & original)
Parameters
original - IN: DataSet instance to copy
References getId(), and H5::IdComponent::incRefCount().
H5::DataSet::DataSet (const hid_t existing_id)
Parameters
existing_id - IN: Id of an existing dataset
H5::DataSet::~DataSet () virtual
References close(), and H5::Exception::getDetailMsg().
Member Function Documentation
void H5::DataSet::close () virtual
Exceptions
H5::DataSetIException
Referenced by ~DataSet().
void H5::DataSet::extend (const hsize_t * size) const
Parameters
size - IN: Array containing the new magnitude of each dimension
Exceptions
H5::DataSetIException
Description
For more information, please see the Description section in C layer Reference Manual at:
http://www.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Extend
Examples:
extend_ds.cpp.
void H5::DataSet::fillMemBuf (const void * fill, const DataType & fill_type, void * buf, const DataType & buf_type, const DataSpace & space) const
Parameters
fill - IN: Pointer to fill value to use - default NULL
fill_type - IN: Datatype of the fill value
buf - IN/OUT: Memory buffer to fill selection within
buf_type - IN: Datatype of the elements in buffer
space - IN: Dataspace describing memory buffer & containing selection to use
Exceptions
H5::DataSetIException
References H5::DataSpace::getId(), and H5::DataType::getId().
Referenced by fillMemBuf().
void H5::DataSet::fillMemBuf (const void * fill, DataType & fill_type, void * buf, DataType & buf_type, DataSpace & space)
Parameters
fill - IN: Pointer to fill value to use - default NULL
fill_type - IN: Datatype of the fill value
buf - IN/OUT: Memory buffer to fill selection within
buf_type - IN: Datatype of the elements in buffer
space - IN: Dataspace describing memory buffer & containing selection to use
Exceptions
H5::DataSetIException
References fillMemBuf().
void H5::DataSet::fillMemBuf (void * buf, const DataType & buf_type, const DataSpace & space) const
Parameters
buf - IN/OUT: Memory buffer to fill selection within
buf_type - IN: Datatype of the elements in buffer
space - IN: Dataspace describing memory buffer & containing selection to use
Exceptions
H5::DataSetIException
References H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::fillMemBuf (void * buf, DataType & buf_type, DataSpace & space)
Parameters
buf - IN/OUT: Memory buffer to fill selection within
buf_type - IN: Datatype of the elements in buffer
space - IN: Dataspace describing memory buffer & containing selection to use
Exceptions
H5::DataSetIException
References fillMemBuf().
virtual H5std_string H5::DataSet::fromClass () const inline virtual
Implements H5::AbstractDs.
DSetCreatPropList H5::DataSet::getCreatePlist () const
Returns
DSetCreatPropList instance
Exceptions
H5::DataSetIException
Examples:
chunks.cpp.
hid_t H5::DataSet::getId () const virtual
Returns
DataSet identifier
Implements H5::H5Location.
Referenced by H5::CompType::CompType(), H5::DataType::copy(), DataSet(), H5::EnumType::EnumType(), H5::FloatType::FloatType(), H5::IntType::IntType(), and H5::StrType::StrType().
size_t H5::DataSet::getInMemDataSize () const virtual
Returns
Size of data (in memory)
Exceptions
H5::DataSetIException
Implements H5::AbstractDs.
haddr_t H5::DataSet::getOffset () const
Returns
Address of dataset
Exceptions
H5::DataSetIException
DataSpace H5::DataSet::getSpace () const virtual
Returns
DataSpace instance
Exceptions
H5::DataSetIException
Implements H5::AbstractDs.
Examples:
chunks.cpp, extend_ds.cpp, readdata.cpp, and writedata.cpp.
void H5::DataSet::getSpaceStatus (H5D_space_status_t & status) const
Parameters
status - OUT: Space allocation status
Exceptions
H5::DataSetIException
hsize_t H5::DataSet::getStorageSize () const virtual
Returns
Size of the storage or 0, for no data
Exceptions
H5::DataSetIException
Implements H5::AbstractDs.
hsize_t H5::DataSet::getVlenBufSize (const DataType & type, const DataSpace & space) const
Returns
Amount of storage
Exceptions
H5::DataSetIException
References H5::DataSpace::getId(), and H5::DataType::getId().
Referenced by getVlenBufSize().
hsize_t H5::DataSet::getVlenBufSize (DataType & type, DataSpace & space) const
Returns
Amount of storage
Exceptions
H5::DataSetIException
References getVlenBufSize().
int H5::DataSet::iterateElems (void * buf, const DataType & type, const DataSpace & space, H5D_operator_t op, void * op_data = NULL)
Parameters
buf - IN/OUT: Pointer to the buffer in memory containing the elements to iterate over
type - IN: Datatype for the elements stored in buf
space - IN: Dataspace for buf. Also contains the selection to iterate over.
op - IN: Function pointer to the routine to be called for each element in buf iterated over
op_data - IN/OUT: Pointer to any user-defined data associated with the operation
Exceptions
H5::DataSetIException
Note
This function may not work correctly yet - it's still under development.
References H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::read (void * buf, const DataType & mem_type, const DataSpace & mem_space = DataSpace::ALL, const DataSpace & file_space = DataSpace::ALL, const DSetMemXferPropList & xfer_plist = DSetMemXferPropList::DEFAULT) const
Parameters
buf - IN: Buffer for read data
mem_type - IN: Memory datatype
mem_space - IN: Memory dataspace
file_space - IN: Dataset's dataspace in the file
xfer_plist - IN: Transfer property list for this I/O operation
Exceptions
H5::DataSetIException
Description
This function reads raw data from this dataset into the buffer buf, converting from file datatype and dataspace to memory datatype mem_type and dataspace mem_space.
Examples:
chunks.cpp, compound.cpp, extend_ds.cpp, readdata.cpp, and writedata.cpp.
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::read (H5std_string & strg, const DataType & mem_type, const DataSpace & mem_space = DataSpace::ALL, const DataSpace & file_space = DataSpace::ALL, const DSetMemXferPropList & xfer_plist = DSetMemXferPropList::DEFAULT) const
Parameters
strg - IN: Buffer for read data string
mem_type - IN: Memory datatype
mem_space - IN: Memory dataspace
file_space - IN: Dataset's dataspace in the file
xfer_plist - IN: Transfer property list for this I/O operation
Exceptions
H5::DataSetIException
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::vlenReclaim (const DataType & type, const DataSpace & space, const DSetMemXferPropList & xfer_plist, void * buf) static
Parameters
type - IN: Datatype, which is the datatype stored in the buffer
space - IN: Selection for the memory buffer to free the VL datatypes within
xfer_plist - IN: Property list used to create the buffer
buf - IN: Pointer to the buffer to be reclaimed
Exceptions
H5::DataSetIException
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::vlenReclaim (void * buf, const DataType & type, const DataSpace & space = DataSpace::ALL, const DSetMemXferPropList & xfer_plist = DSetMemXferPropList::DEFAULT) static
Parameters
type - IN: Datatype, which is the datatype stored in the buffer
space - IN: Selection for the memory buffer to free the VL datatypes within
xfer_plist - IN: Property list used to create the buffer
buf - IN: Pointer to the buffer to be reclaimed
Exceptions
H5::DataSetIException
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::write (const void * buf, const DataType & mem_type, const DataSpace & mem_space = DataSpace::ALL, const DataSpace & file_space = DataSpace::ALL, const DSetMemXferPropList & xfer_plist = DSetMemXferPropList::DEFAULT) const
Parameters
buf - IN: Buffer containing data to be written
mem_type - IN: Memory datatype
mem_space - IN: Memory dataspace
file_space - IN: Dataset's dataspace in the file
xfer_plist - IN: Transfer property list for this I/O operation
Exceptions
H5::DataSetIException
Description
This function writes raw data from an application buffer buf to a dataset, converting from memory datatype mem_type and dataspace mem_space to file datatype and dataspace.
Examples:
compound.cpp, create.cpp, extend_ds.cpp, and writedata.cpp.
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
void H5::DataSet::write (const H5std_string & buf, const DataType & mem_type, const DataSpace & mem_space = DataSpace::ALL, const DataSpace & file_space = DataSpace::ALL, const DSetMemXferPropList & xfer_plist = DSetMemXferPropList::DEFAULT) const
References H5::PropList::getId(), H5::DataSpace::getId(), and H5::DataType::getId().
The documentation for this class was generated from the following files:
H5DataSet.h
H5DataSet.cpp