HDF5 C++ API: H5::IdComponent Class Reference
H5::IdComponent Class Reference
Class IdComponent provides wrappers of the C functions that operate on an HDF5 identifier.
#include <H5IdComponent.h>
Public Member Functions
void incRefCount (const hid_t obj_id) const
Increment reference counter for a given id.
void incRefCount () const
Increment reference counter for the id of this object.
void decRefCount (const hid_t obj_id) const
Decrement reference counter for a given id.
void decRefCount () const
Decrement reference counter for the id of this object.
int getCounter (const hid_t obj_id) const
Returns the reference counter for a given id.
int getCounter () const
Returns the reference counter for the id of this object.
H5I_type_t getHDFObjType () const
Returns the type of the object. It is an overloaded function of the above function.
IdComponent & operator= (const IdComponent &rhs)
Assignment operator.
void setId (const hid_t new_id)
Sets the identifier of this object to a new value.
IdComponent (const hid_t h5_id)
Creates an IdComponent object using the id of an existing object.
IdComponent (const IdComponent &original)
Copy constructor: makes a copy of the original IdComponent object.
virtual ~IdComponent ()
Noop destructor.
Static Public Member Functions
static H5I_type_t getHDFObjType (const hid_t obj_id)
Given an id, returns the type of the object.
Protected Member Functions
IdComponent ()
Detailed Description
In most cases, the C library handles these operations and an application rarely needs them.
Constructor & Destructor Documentation
H5::IdComponent::IdComponent (const hid_t h5_id)
Parameters
h5_id - IN: Id of an existing object
Exceptions
H5::DataTypeIException
H5::IdComponent::IdComponent (const IdComponent & original)
Parameters
original - IN: IdComponent instance to copy
H5::IdComponent::~IdComponent () virtual
H5::IdComponent::IdComponent () protected
Member Function Documentation
void H5::IdComponent::decRefCount (const hid_t obj_id) const
void H5::IdComponent::decRefCount () const
int H5::IdComponent::getCounter (const hid_t obj_id) const
Returns
Reference count
int H5::IdComponent::getCounter () const
Returns
Reference count
H5I_type_t H5::IdComponent::getHDFObjType (const hid_t obj_id) static
Returns
a valid HDF object type, which may be one of the following:
H5I_FILE
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
or H5I_BADID, if no valid type can be determined or the input object id is invalid.
H5I_type_t H5::IdComponent::getHDFObjType () const
Returns
a valid HDF object type, which may be one of the following:
H5I_FILE
H5I_GROUP
H5I_DATATYPE
H5I_DATASPACE
H5I_DATASET
H5I_ATTR
or H5I_BADID, if no valid type can be determined or the input object id is invalid.
void H5::IdComponent::incRefCount (const hid_t obj_id) const
void H5::IdComponent::incRefCount () const
Referenced by H5::Attribute::Attribute(), H5::DataSet::DataSet(), H5::DataSpace::DataSpace(), H5::DataType::DataType(), H5::Group::Group(), H5::H5File::H5File(), H5::PropList::PropList(), and setId().
IdComponent & H5::IdComponent::operator= (const IdComponent & rhs)
Parameters
rhs - IN: Reference to the existing object
Returns
Reference to IdComponent instance
Exceptions
H5::IdComponentException when attempt to close the HDF5 object fails
References H5::Exception::getDetailMsg(), and setId().
void H5::IdComponent::setId (const hid_t new_id)
Exceptions
H5::IdComponentException when the attempt to close the HDF5 object fails
References incRefCount().
Referenced by operator=().
The documentation for this class was generated from the following files:
H5IdComponent.h
H5IdComponent.cpp