cmake_minimum_required (VERSION 3.18)
project (HDF5_CPP CXX)

if (NOT HDF5_USE_HIGH_FIVE)
  add_subdirectory (src)
else ()
  option (HIGHFIVE_USE_EXTERNAL "Use External Library Building for ZLIB" OFF)
  if (NOT HIGHFIVE_USE_LOCALCONTENT)
    set (HIGHFIVE_URL ${HIGHFIVE_TGZ_ORIGPATH}/${HIGHFIVE_TGZ_NAME})
  else ()
    set (HIGHFIVE_URL ${TGZPATH}/${HIGHFIVE_TGZ_NAME})
  endif ()
  message (VERBOSE "Filter HighFive file is ${HIGHFIVE_URL}")

  if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT" OR HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
    set (HIGHFIVE_USE_EXTERNAL ON CACHE BOOL "Use External Library Building for HighFive else search" FORCE)
    if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT")
      set (HIGHFIVE_URL ${HIGHFIVE_GIT_URL} CACHE STRING "Path to HighFive git repository")
      set (HIGHFIVE_BRANCH ${HIGHFIVE_GIT_BRANCH})
    elseif (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
      if (NOT TGZPATH)
        set (TGZPATH ${HDF5_SOURCE_DIR})
      endif ()
      if (HIGHFIVE_USE_LOCALCONTENT)
        if (NOT EXISTS "${HIGHFIVE_URL}")
          set (HDF5_BUILD_CPP_LIB OFF CACHE BOOL "" FORCE)
          message (VERBOSE "Filter HighFive file ${HIGHFIVE_URL} not found")
        endif ()
      endif ()
    else ()
      set (HDF5_BUILD_CPP_LIB OFF CACHE BOOL "" FORCE)
      set (HIGHFIVE_USE_EXTERNAL OFF CACHE BOOL "Use External Library Building for HighFive else search")
    endif ()
  endif ()

  set (H5_HIGHFIVE_FOUND FALSE)
  if (NOT HIGHFIVE_USE_EXTERNAL)
    set (HIGHFIVE_FOUND FALSE)
    find_package (HIGHFIVE NAMES HighFive REQUIRED)
    set (H5_HIGHFIVE_FOUND ${HIGHFIVE_FOUND})
    if (H5_HIGHFIVE_FOUND)
      set (H5_HIGHFIVE_INCLUDE_DIRS ${HighFive_INCLUDE_DIRS} PARENT_SCOPE)
      set (H5_HIGHFIVE_LIBS HighFive::Include PARENT_SCOPE)
    endif ()
  else ()
    if (HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "GIT" OR HDF5_ALLOW_EXTERNAL_SUPPORT MATCHES "TGZ")
      EXTERNAL_HIGHFIVE_LIBRARY (${HDF5_ALLOW_EXTERNAL_SUPPORT})
      message (VERBOSE "Filter HIGHFIVE is built")
      set (H5_HIGHFIVE_INCLUDE_DIRS ${H5_HIGHFIVE_INCLUDE_DIR} PARENT_SCOPE)
      set (H5_HIGHFIVE_LIBS ${H5_HIGHFIVE_LIBRARY} PARENT_SCOPE)
    endif ()
  endif ()
  message (VERBOSE "HIGHFIVE LIB: ${H5_HIGHFIVE_LIBS} INCLUDE: ${H5_HIGHFIVE_INCLUDE_DIRS}")
endif ()

#-----------------------------------------------------------------------------
# Build the CPP unit tests
#-----------------------------------------------------------------------------
if (NOT HDF5_EXTERNALLY_CONFIGURED AND BUILD_TESTING)
  if (NOT HDF5_USE_HIGH_FIVE)
    add_subdirectory (test)
  endif ()
endif ()
