The release timeline was generated on PlantUML (https://plantuml.com)

The current script:
@startgantt

title HDF5 Release Schedule

projectscale monthly
Project starts 2024-09-01

[1.14] starts at 2024-09-01 and lasts 30 weeks
[1.14.5] happens at 2024-09-30
[1.14.6 (EOL)] happens at 2025-01-30
[1.14.5] displays on same row as [1.14.5]
[1.14.6 (EOL)] displays on same row as [1.14.5]
[1.14] is colored in #F76969

[2.x] starts at 2025-01-31 and lasts 90 weeks
[2.0.0] happens at 2025-10-25
[2.1.0] happens at 2026-03-03
[2.2.0] happens at 2026-07-27
[2.0.0] displays on same row as [2.0.0]
[2.1.0] displays on same row as [2.0.0]
[2.2.0] displays on same row as [2.0.0]
[2.x] is colored in #44ffaa

@endgantt
