The release timeline was generated on PlantUML (https://plantuml.com)

The current script:

@startuml
title HDF5 Release Schedule

projectscale monthly
Project starts 2022-01-01

[1.8] starts 2022-01-01 and lasts 57 weeks
[1.8.23] happens 2023-01-31
[1.8] is colored in #CC6677

[1.10] starts 2022-01-01 and lasts 104 weeks
[1.10.9] happens 2022-05-31
[1.10.10] happens 2023-03-31
[1.10.10] displays on same row as [1.10.9]
[1.10] is colored in #DDCC77

[1.12] starts 2022-01-01 and lasts 61 weeks
[1.12.2] happens 2022-04-30
[1.12.3] happens 2023-02-28
[1.12.3] displays on same row as [1.12.2]
[1.12] is colored in #88CCEE

[1.13] starts 2022-01-01 and lasts 53 weeks
[1.13.1] happens 2022-03-02
[1.13.2] happens 2022-08-15
[1.13.3] happens 2022-10-31
[1.13.2] displays on same row as [1.13.1]
[1.13.3] displays on same row as [1.13.1]
[1.13] is colored in #44AA99

[1.14] starts at 2023-01-01 and lasts 52 weeks
[1.14.0] happens at 2023-01-01
[1.14.1] happens at 2023-06-30
[1.14] displays on same row as [1.13]
[1.14.0] displays on same row as [1.13.1]
[1.14.1] displays on same row as [1.13.1]
[1.14] is colored in #AA4499
@enduml

