name: hdf5 dev PAR aocc ompi

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  aocc_build_and_test:
    name: "aocc ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    env:
      AOCCVERDOT: "5.1.0"
      AOCCVERDASH: "5-1"
      MPIVERDOT: "5.0.9"
      #MPIVERUND: Change is needed in the lines below.

    steps:
      - name: Get Sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libaec-dev ninja-build
          sudo apt install -y doxygen libncurses-dev libquadmath0 libstdc++6 libxml2
          sudo apt install -y zlib1g-dev libcurl4-openssl-dev libjpeg-dev wget curl bzip2
          sudo apt install -y m4 flex bison cmake libzip-dev openssl build-essential

      - name: Install ${{ env.AOCCVERDOT }} AOCC
        shell: bash
        env:
          ENV_AOCCVERDASH: ${{ env.AOCCVERDASH }}
          ENV_AOCCVERDOT: ${{ env.AOCCVERDOT }}
        run: |
          wget https://download.amd.com/developer/eula/aocc/aocc-$ENV_AOCCVERDASH/aocc-compiler-$ENV_AOCCVERDOT.tar
          tar -xvf aocc-compiler-$ENV_AOCCVERDOT.tar
          cd aocc-compiler-$ENV_AOCCVERDOT
          bash install.sh
          source /home/runner/work/hdf5/hdf5/setenv_AOCC.sh
          which clang
          which flang
          clang -v

      - name: Cache OpenMPI ${{ env.MPIVERDOT }} installation
        id: cache-openmpi-5_0_7
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v4
        with:
          path: /home/runner/work/hdf5/hdf5/openmpi-${{ env.MPIVERDOT }}-install
          key: ${{ runner.os }}-${{ runner.arch }}-openmpi-5_0_7-cache

      - name: Install OpenMPI ${{ env.MPIVERDOT }}
        if: ${{ steps.cache-openmpi-5_0_7.outputs.cache-hit != 'true' }}
        env:
          ENV_AOCCVERDOT: ${{ env.AOCCVERDOT }}
          ENV_MPIVERDOT: ${{ env.MPIVERDOT }}
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/hdf5/hdf5/aocc-compiler-$ENV_AOCCVERDOT/lib:/usr/local/lib
          wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-$ENV_MPIVERDOT.tar.gz
          tar zxvf openmpi-$ENV_MPIVERDOT.tar.gz
          cd openmpi-$ENV_MPIVERDOT
          ./configure CC=/home/runner/work/hdf5/hdf5/aocc-compiler-$ENV_AOCCVERDOT/bin/clang FC=/home/runner/work/hdf5/hdf5/aocc-compiler-$ENV_AOCCVERDOT/bin/flang --prefix=/home/runner/work/hdf5/hdf5/openmpi-$ENV_MPIVERDOT-install
          make
          make install

      - name: Configure
        shell: bash
        env:
          ENV_AOCCVERDOT: ${{ env.AOCCVERDOT }}
          ENV_MPIVERDOT: ${{ env.MPIVERDOT }}
          INPUT_BUILD_MODE: ${{ inputs.build_mode }}
        run: |
          export LD_LIBRARY_PATH=/home/runner/work/hdf5/hdf5/aocc-compiler-$ENV_AOCCVERDOT/lib:/home/runner/work/hdf5/hdf5/openmpi-$ENV_MPIVERDOT-install/lib:/usr/local/lib
          export LD_RUN_PATH=/home/runner/work/hdf5/hdf5/aocc-compiler-$ENV_AOCCVERDOT/lib:/home/runner/work/hdf5/hdf5/openmpi-$ENV_MPIVERDOT-install/lib:/usr/local/lib
          export PATH=/home/runner/work/hdf5/hdf5/openmpi-$ENV_MPIVERDOT-install/bin:/usr/local/bin:$PATH
          mkdir "$RUNNER_WORKSPACE/build"
          cd "$RUNNER_WORKSPACE/build"
          CC=mpicc cmake -C $GITHUB_WORKSPACE/config/cmake/cacheinit.cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=$INPUT_BUILD_MODE \
          -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_PARALLEL:BOOL=ON \
          -DHDF5_ENABLE_SUBFILING_VFD:BOOL=ON \
          -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
          -DLIBAEC_USE_LOCALCONTENT=OFF \
          -DZLIB_USE_LOCALCONTENT=OFF \
          -DHDF5_BUILD_FORTRAN:BOOL=OFF \
          -DHDF5_BUILD_JAVA:BOOL=OFF \
          -DMPIEXEC_MAX_NUMPROCS:STRING="2" \
          $GITHUB_WORKSPACE
          #cat src/libhdf5.settings

      - name: Build
        shell: bash
        env:
          INPUT_BUILD_MODE: ${{ inputs.build_mode }}
        run: |
          cmake --build . --parallel 3 --config $INPUT_BUILD_MODE
        working-directory: ${{ runner.workspace }}/build

      - name: Run Tests
        shell: bash
        env:
          INPUT_BUILD_MODE: ${{ inputs.build_mode }}
        run: |
          ctest . -E MPI_TEST --parallel 2 -C $INPUT_BUILD_MODE
        working-directory: ${{ runner.workspace }}/build

      - name: Run Parallel Tests
        shell: bash
        env:
          INPUT_BUILD_MODE: ${{ inputs.build_mode }}
        run: |
          ctest . -R MPI_TEST -E "_by_chunk|_by_pattern" -C $INPUT_BUILD_MODE
        working-directory: ${{ runner.workspace }}/build
