name: hdf5 dev big-endian (s390x)

# Triggers the workflow on a call from another workflow
on:
  push:
    branches:
      - feature/ci-bigendian-s390x
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: choice
        options:
          - Release
          - Debug
        default: Release

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  BUILD_MODE: ${{ inputs.build_mode || 'Release' }}

jobs:
  bigendian_build_and_test:
    name: "s390x (big-endian) ${{ inputs.build_mode || 'Release' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Alpine (s390x)
        uses: jirutka/setup-alpine@ae3b3ddba35054804fc4a3507b519fa7e8152050 # v1
        with:
          arch: s390x
          packages: >
            build-base
            cmake
            python3
            gfortran

      - name: Verify big-endian
        shell: alpine.sh --root {0}
        run: |
          python3 -c "import sys; assert sys.byteorder == 'big', 'Not big-endian!'; print('Confirmed big-endian')"

      - name: Configure
        shell: alpine.sh --root {0}
        run: |
          mkdir build
          cd build
          cmake -C ../config/cmake/cacheinit.cmake -G "Unix Makefiles" \
          --log-level=VERBOSE \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} \
          -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
          -DHDF5_ENABLE_PLUGIN_SUPPORT:BOOL=OFF \
          -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
          -DHDF5_BUILD_FORTRAN:BOOL=ON \
          -DHDF5_BUILD_JAVA:BOOL=OFF \
          -DHDF5_BUILD_DOC:BOOL=OFF \
          ..

      - name: Build
        shell: alpine.sh --root {0}
        run: |
          cmake --build . --parallel 2 --config ${{ env.BUILD_MODE }}
        working-directory: build

      - name: Run Tests
        shell: alpine.sh --root {0}
        run: |
          ctest . --parallel 2 -C ${{ env.BUILD_MODE }} --timeout 1800 \
            -E "FORTRAN_testhdf5_fortran"
        working-directory: build
