name: hdf5 dev big-endian (s390x)

# Triggers the workflow on a call from another workflow
on:
  workflow_call:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      build_mode:
        description: "release vs. debug build"
        required: true
        type: choice
        options:
          - Release
          - Debug
        default: Release

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  bigendian_build_and_test:
    name: "s390x (big-endian) ${{ inputs.build_mode }}"
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build and Test (s390x big-endian)
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y build-essential cmake python3 gfortran
          run: |
            python3 -c "import sys; assert sys.byteorder == 'big', 'Not big-endian!'; print('Confirmed big-endian')"
            mkdir build
            cd build
            cmake -C ../config/cmake/cacheinit.cmake -G "Unix Makefiles" \
            --log-level=VERBOSE \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=OFF \
            -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=OFF \
            -DHDF5_ENABLE_PLUGIN_SUPPORT:BOOL=OFF \
            -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
            -DHDF5_BUILD_FORTRAN:BOOL=ON \
            -DHDF5_BUILD_JAVA:BOOL=OFF \
            -DHDF5_BUILD_DOC:BOOL=OFF \
            ..
            cmake --build . --parallel 1 --config ${{ inputs.build_mode }}
            ctest . --parallel 2 -C ${{ inputs.build_mode }} --timeout 1800 \
              -E "H5_H5DUMP-h5ex_image2"
