name: hdf5 dev cmake CI

# Triggers the workflow on push or pull request or on demand
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.github/FUNDING.yml'
      - 'doc/**'
      - 'release_docs/**'
      - 'ACKNOWLEDGEMENTS'
      - 'LICENSE**'
      - '**.md'

# Using concurrency to cancel any in-progress job or run
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    call-workflow-special-cmake:
      name: "CMake Special Workflows"
      uses: ./.github/workflows/main-cmake-spc.yml

    call-debug-thread-cmake:
        name: "CMake Debug Thread-Safety Workflows"
        uses: ./.github/workflows/main-cmake.yml
        with:
            thread_safety: "TS"
            build_mode: "Debug"

    call-release-thread-cmake:
        name: "CMake Release Thread-Safety Workflows"
        uses: ./.github/workflows/main-cmake.yml
        with:
            thread_safety: "TS"
            build_mode: "Release"

    call-debug-cmake:
        name: "CMake Debug Workflows"
        uses: ./.github/workflows/main-cmake.yml
        with:
            thread_safety: ""
            build_mode: "Debug"

    call-release-cmake:
        name: "CMake Release Workflows"
        uses: ./.github/workflows/main-cmake.yml
        with:
            thread_safety: ""
            build_mode: "Release"

    call-release-bintest:
        name: "CMake Test Release Binaries"
        needs: call-release-cmake
        uses: ./.github/workflows/cmake-bintest.yml
        with:
            build_mode: "Release"

    call-release-par:
        name: "CMake Parallel Release Workflows"
        uses: ./.github/workflows/main-cmake-par.yml
        with:
            build_mode: "Release"

    call-debug-par:
        name: "CMake Parallel Debug Workflows"
        uses: ./.github/workflows/main-cmake-par.yml
        with:
            build_mode: "Debug"

    call-release-special-par:
        name: "CMake Parallel Release Special Workflows"
        uses: ./.github/workflows/main-cmake-par-spc.yml
        with:
            build_mode: "Release"

    call-debug-special-par:
        name: "CMake Parallel Debug Special Workflows"
        uses: ./.github/workflows/main-cmake-par-spc.yml
        with:
            build_mode: "Debug"

    call-release-cmake-intel:
        name: "CMake Intel Workflows"
        uses: ./.github/workflows/intel-cmake.yml
        with:
            build_mode: "Release"

    call-release-cmake-nvhpc:
        name: "CMake nvhpc Workflows"
        uses: ./.github/workflows/nvhpc-cmake.yml
        with:
            build_mode: "Release"

    call-release-cmake-aocc:
        name: "CMake aocc Workflows"
        uses: ./.github/workflows/aocc-cmake.yml
        with:
            build_mode: "Release"

    call-release-cmake-cygwin:
        name: "CMake Cygwin Workflows"
        uses: ./.github/workflows/cygwin-cmake.yml
        with:
            build_mode: "Release"

    call-release-cmake-xpr:
        name: "CMake TestExpress Workflows"
        uses: ./.github/workflows/testxpr-cmake.yml

#    call-release-cmake-julia:
#        name: "CMake Julia Workflows"
#        uses: ./.github/workflows/julia-cmake.yml
#        with:
#          build_mode: "Release"      
