name: hdf5 Developer Mode CMake CI

on:
  workflow_call:
    inputs:
      file_base:
        description: "The common base name of the source tarballs"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_and_test:
    name: "CMake Developer Mode Express Test Workflows"

    # Don't run the action if the commit message says to skip CI
    if: "!contains(github.event.head_commit.message, 'skip-ci')"

    runs-on: ubuntu-latest
    steps:
      - name: Set file base name (Windows)
        id: set-file-base
        run: |
           FILE_NAME_BASE=$(echo "${{ inputs.file_base }}")
           echo "FILE_BASE=$FILE_NAME_BASE" >> $GITHUB_OUTPUT

      - name: Install Linux Dependencies
        run: |
           sudo apt-get update
           sudo apt-get install ninja-build doxygen graphviz
           sudo apt install libssl3 libssl-dev libcurl4 libcurl4-openssl-dev
           sudo apt install libaec0 libaec-dev
           sudo apt install gcc-12 g++-12 gfortran-12
           echo "CC=gcc-12" >> $GITHUB_ENV
           echo "CXX=g++-12" >> $GITHUB_ENV
           echo "FC=gfortran-12" >> $GITHUB_ENV

      # Get files created by release script
      - name: Get tgz-tarball (Linux)
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
              name: tgz-tarball
              path: ${{ github.workspace }}

      - name: List files for the space (Linux)
        run: |
              ls -l ${{ github.workspace }}
              ls ${{ runner.workspace }}

      - name: Uncompress source (Linux)
        run: tar -zxvf ${{ github.workspace }}/${{ steps.set-file-base.outputs.FILE_BASE }}.tar.gz

      - name: Get Sources
        uses: actions/checkout@v4.1.7

      - name: CMake Configure
        shell: bash
        run: |
            mkdir "${{ runner.workspace }}/build"
            cd "${{ runner.workspace }}/build"
            cd ""
            cmake -C ${{ runner.workspace }}/hdf5/${{ steps.set-file-base.outputs.FILE_BASE }}/config/cmake/cacheinit.cmake \
                 -G Ninja \
                 -DCMAKE_BUILD_TYPE=Developer \
                 -DBUILD_SHARED_LIBS=ON \
                 -DHDF5_ENABLE_ALL_WARNINGS=ON \
                 -DHDF5_ENABLE_PARALLEL:BOOL=OFF \
                 -DHDF5_BUILD_CPP_LIB:BOOL=OFF \
                 -DHDF5_BUILD_FORTRAN=OFF \
                 -DHDF5_BUILD_JAVA=OFF \
                 -DHDF5_BUILD_DOC=OFF \
                 -DLIBAEC_USE_LOCALCONTENT=OFF \
                 -DZLIB_USE_LOCALCONTENT=OFF \
                 -DHDF_TEST_EXPRESS=0 \
                 $GITHUB_WORKSPACE

      - name: CMake Build
        run: cmake --build . --parallel 3 --config Developer
        working-directory: ${{ runner.workspace }}/build

      - name: CMake Run Tests
        env:
          HDF5TestExpress: 0
        run: ctest . --parallel 2 -C Developer -V -R H5TESTXPR
        working-directory: ${{ runner.workspace }}/build
