name: h5py

# Triggers the workflow on a schedule or on demand
on:
  workflow_dispatch:
  schedule:
    - cron: "6 0 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v4.1.7
      with:
        repository: spack/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        sed -i 's/hdf5@1.10.4:1.14/hdf5@1.10.4:/g' \
        ./spack/var/spack/repos/builtin/packages/py-h5py/package.py
        . ./spack/share/spack/setup-env.sh
        ./spack/bin/spack spec py-h5py@master+mpi ^hdf5@develop-1.17
        ./spack/bin/spack install py-h5py@master+mpi ^hdf5@develop-1.17
        ./spack/bin/spack install py-pytest
        ./spack/bin/spack install py-ipython
        ./spack/bin/spack install py-pytest-mpi        
        spack load py-h5py
        spack load py-pytest
        spack load py-ipython
        spack load py-pytest-mpi
        python -c "import h5py; h5py.run_tests(); print(h5py.version.info);"
