name: ubuntu hdf5@develop+mpi+fortran

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spack
      uses: actions/checkout@v3
      with:
        repository: spack/spack
        path: ./spack

    - name: Run a multi-line script
      run: |
        cd ./spack
        . ./share/spack/setup-env.sh
        spack spec hdf5@develop+mpi+fortran
        spack install hdf5@develop+mpi+fortran
      
