name: hdf5 dev CMake s3proxy CI

# Controls when the action will run. Triggers the workflow on a call
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel. We just have one job, but the matrix items defined below will
# run in parallel.
jobs:
  build_linux_ros3:
      name: "ros3 proxy tests"
      runs-on: ubuntu-latest
      steps:
        # SETUP
        - name: Install Linux Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install ninja-build doxygen graphviz
            sudo apt install libssl3 libssl-dev libcurl4 libcurl4-openssl-dev

        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Get Sources
          uses: actions/checkout@v4.1.7

        # CMAKE CONFIGURE
        - name: CMake Configure
          run: |
            mkdir "${{ runner.workspace }}/build"
            cd "${{ runner.workspace }}/build"
            cmake -C $GITHUB_WORKSPACE/config/cmake/cacheinit.cmake \
              -G Ninja \
              --log-level=VERBOSE \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DHDF5_ENABLE_ALL_WARNINGS=ON \
              -DHDF5_ENABLE_PARALLEL:BOOL=OFF \
              -DHDF5_BUILD_FORTRAN:BOOL=ON \
              -DHDF5_BUILD_CPP_LIB:BOOL=ON \
              -DHDF5_ENABLE_ZLIB_SUPPORT:BOOL=ON \
              -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON \
              -DHDF5_ENABLE_SZIP_ENCODING:BOOL=ON \
              -DHDF5_ENABLE_PLUGIN_SUPPORT:BOOL=ON \
              -DLIBAEC_USE_LOCALCONTENT=OFF \
              -DZLIB_USE_LOCALCONTENT=OFF \
              -DHDF5_ENABLE_DOCKER_PROXY=ON \
              $GITHUB_WORKSPACE
          shell: bash

        # BUILD
        - name: CMake Build
          run: cmake --build . --parallel 3 --config Release
          working-directory: ${{ runner.workspace }}/build

        # RUN TESTS
        - name: CMake Run Tests
          run: ctest . --parallel 2 -C Release -V
          working-directory: ${{ runner.workspace }}/build
